using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using SMB4.Engine;
using SMB4.Game;

namespace SMB4.Tools
{
    public static partial class SnesExport
    {
        /// <summary>Export step: levels+tiles (engine agent, see snes/DESIGN.md "Level data contract").</summary>
        static int ExportLevels(string outDir) { return SnesLevels.Export(outDir); }
    }

    /// <summary>
    /// Converts data/levels (through the C# LevelLoader, so the grids are exactly what the Windows game sees) and the
    /// level tiles of data/art into SNES data for the engine (snes/src/game.s + eng_*.s):
    ///  * gen/levels.inc  constants (LEVEL_COUNT, T_* tile types, CT_* contents, engine tileset ids)
    ///  * gen/eng_levels.s  level directory, level/area headers, LZ-compressed tile + metatile grids, sparse lists
    ///  * gen/eng_tiles.s  per-theme BG1 tilesets: 4bpp CHR, metatile table (4 tilemap words each), 4 palettes of 15
    ///    colors (BG palettes 2-5), animated CHR frames, runtime metatile table for tiles that change
    ///  * gen/eng_font.s  2bpp HUD/menu font for BG3
    /// Data goes only into BANK40-BANK55 (see DESIGN.md "API requests").
    /// </summary>
    public static class SnesLevels
    {
        public const int FirstBank = 40, LastBank = 51;
        public static readonly string[] Themes = { "plains", "underground", "desert", "sea", "jungle", "sky", "ice", "machine", "volcano", "fortress", "castle", "airship", "bonus" };
        public static readonly string[] Scrolls = { "normal", "free", "lock", "vertical", "auto" };

        /// <summary>Level order used by the level select and "next level" (world by world: 1..5, fortress, airship/castle).</summary>
        public static List<string> LevelOrder()
        {
            var ids = new List<string>();
            foreach (var p in Data.List("levels/"))
            {
                if (!p.EndsWith(".lvl", StringComparison.OrdinalIgnoreCase)) continue;
                string id = Path.GetFileNameWithoutExtension(p);
                if (id.StartsWith("_") || id.Length != 3 || id[1] != '-' || !char.IsDigit(id[0])) continue;
                ids.Add(id);
            }
            ids.Sort((a, b) => Rank(a).CompareTo(Rank(b)));
            // the Hammer Bro battle arena (entered from the map) is last: LVL_HB (= the sprites module's SPR_LEVEL_HB)
            foreach (var p in Data.List("levels/"))
                if (string.Equals(Path.GetFileName(p), "hb.lvl", StringComparison.OrdinalIgnoreCase)) { ids.Add("hb"); break; }
            return ids;
        }

        static int Rank(string id)
        {
            int w = id[0] - '0';
            char c = id[2];
            int k = char.IsDigit(c) ? c - '0' : c == 'f' ? 10 : c == 'a' ? 11 : c == 'c' ? 12 : 13;
            return w * 100 + k;
        }

        // ------------------------------------------------------------------------------------------------ export
        public static int Export(string outDir)
        {
            // other modules' include files may not exist yet (their steps run later / may fail): empty stubs
            foreach (var inc0 in new[] { "music.inc", "themes.inc", "spr_ids.inc" })
            {
                string f0 = Path.Combine(outDir, inc0);
                if (!File.Exists(f0)) File.WriteAllText(f0, "; stub (created by the levels step)" + Environment.NewLine);
            }
            var order = LevelOrder();
            var defs = new List<LevelDef>();
            foreach (var id in order)
            {
                var d = LevelLoader.Load(id);
                if (d == null) { Console.WriteLine("  levels: cannot load " + id); return 1; }
                defs.Add(d);
            }
            var packer = new BankPacker();

            // ---------------- tilesets (one per theme used)
            var tilesets = new Dictionary<string, Tileset>();
            foreach (var d in defs)
                foreach (var a in d.Areas)
                {
                    Tileset ts;
                    if (!tilesets.TryGetValue(a.Theme, out ts)) { ts = new Tileset(a.Theme); tilesets[a.Theme] = ts; }
                    ts.AddArea(a);
                }
            var tsOut = new StringBuilder();
            tsOut.AppendLine("; generated by smb4tools snes-export (SnesLevels.cs) - BG1 tilesets");
            tsOut.AppendLine(".p816");
            tsOut.AppendLine(".export eng_ts_dir");
            var tsDir = new List<string>();
            int errors = 0;
            foreach (var th in Themes)
            {
                Tileset ts;
                if (!tilesets.TryGetValue(th, out ts)) { tsDir.Add(null); continue; }
                errors += ts.Build();
                ts.Emit(packer, tsDir.Count);
                tsDir.Add("ts_" + th);
                Console.WriteLine("  tileset " + th + ": " + ts.Summary());
            }
            // ---------------- levels
            var lv = new StringBuilder();
            var dirNames = new List<string>();
            for (int li = 0; li < defs.Count; li++)
            {
                var d = defs[li];
                string lname = "lvl_" + Sym(d.Id);
                var areaNames = new List<string>();
                for (int ai = 0; ai < d.Areas.Count; ai++)
                {
                    var a = d.Areas[ai];
                    string an = lname + "_a" + ai;
                    areaNames.Add(an);
                    EmitArea(packer, an, a, tilesets[a.Theme]);
                }
                var b = new Blob(lname);
                int world = char.IsDigit(d.Id[0]) ? d.Id[0] - '0' : 9;   // hb: row 9 of the test level select
                int kind = d.Kind == "battle" ? 1 : d.Kind == "fortress" ? 2 : d.Kind == "airship" ? 3 : d.Kind == "castle" ? 4 : 0;
                b.Byte(world); b.Byte(kind); b.Word(d.Time);
                b.Byte(d.StartArea); b.Byte(d.StartX); b.Byte(d.StartY); b.Byte(d.Areas.Count);
                b.Byte(d.Links.Count);
                string nm = d.Id.ToUpperInvariant();
                for (int i = 0; i < 4; i++) b.Byte(i < nm.Length ? nm[i] : ' ');
                string title = (d.Title ?? "").ToUpperInvariant();
                for (int i = 0; i < 20; i++) b.Byte(i < title.Length ? title[i] : ' ');
                foreach (var an in areaNames) b.Far(an);
                foreach (var l in d.Links) { b.Byte(l.FromArea); b.Byte(l.FromId); b.Byte(l.ToArea); b.Byte(l.ToId); }
                packer.Add(b);
                dirNames.Add(lname);
            }
            // level directory
            var dir = new Blob("eng_lvl_dir");
            foreach (var n in dirNames) dir.Far(n);
            packer.Add(dir);
            var tsd = new Blob("eng_ts_dir");
            foreach (var n in tsDir) { if (n == null) tsd.Raw("\t.faraddr 0"); else tsd.Far(n); }
            packer.Add(tsd);

            // ---------------- font
            var font = new Blob("eng_font");
            for (int c = 32; c < 96; c++) font.Bytes(FontTile((char)c));
            // extra glyphs 64..: filled arrow, empty arrow, P badge left/right, 'x' small, frame bits
            packer.Add(font);

            // trig tables for the C# Math.Sin motions (exact (int) truncation of the C# doubles)
            var tb = new Blob("eng_tables");
            for (int t = 0; t < 180; t++) tb.Word((int)(Math.Sin(t * 2 * Math.PI / 180.0) * 40 * 16));
            for (int t = 0; t < 240; t++) tb.Word((int)(Math.Sin(t * 2 * Math.PI / 240.0) * 48 * 16));
            for (int t = 0; t < 240; t++) tb.Word(Math.Cos(t * 2 * Math.PI / 240.0) > 0 ? 1 : 0xFFFF);
            for (int t = 0; t < 240; t++) tb.Word((int)(Math.Sin(t * 2 * Math.PI / 240.0) * 56 * 16));   // MovingLift x
            // +1800: generic binary-angle sine for ent_sin (256 steps per turn, value = sin * 32767)
            for (int t = 0; t < 256; t++) tb.Word((int)Math.Round(Math.Sin(t * 2 * Math.PI / 256.0) * 32767));
            packer.Add(tb);

            string asm = packer.Emit(new[] { "eng_lvl_dir", "eng_ts_dir", "eng_font", "eng_tables" });
            if (asm == null) { Console.WriteLine("  levels: ROM banks " + FirstBank + "-" + LastBank + " are full"); return 1; }
            File.WriteAllText(Path.Combine(outDir, "eng_data.s"), "; generated by smb4tools snes-export (SnesLevels.cs)\n.p816\n" +
                "; tolerate missing theme / song symbols from other modules' stubs\n" + SymbolFallbacks(defs) + asm);

            // ---------------- constants
            var inc = new StringBuilder();
            inc.AppendLine("; generated by smb4tools snes-export (SnesLevels.cs)");
            inc.AppendLine("LEVEL_COUNT = " + defs.Count);
            for (int i = 0; i < defs.Count; i++) inc.AppendLine("LVL_" + Sym(defs[i].Id).ToUpperInvariant() + " = " + i);
            for (int i = 0; i < Themes.Length; i++) inc.AppendLine("ETS_" + Themes[i].ToUpperInvariant() + " = " + i);
            foreach (T t in Enum.GetValues(typeof(T))) inc.AppendLine("T_" + t.ToString().ToUpperInvariant() + " = " + (int)t);
            foreach (Content c in Enum.GetValues(typeof(Content))) inc.AppendLine("CT_" + c.ToString().ToUpperInvariant() + " = " + (int)c);
            for (int i = 0; i < Scrolls.Length; i++) inc.AppendLine("SCROLL_" + Scrolls[i].ToUpperInvariant() + " = " + i);
            inc.AppendLine("DYN_EMPTY = 0\nDYN_COIN = 1\nDYN_BRICK = 2\nDYN_USED = 3\nDYN_VINE = 4\nDYN_VINETOP = 5\nDYN_MUNCHER = 6\nDYN_QBLOCK = 7");
            // tile-type property table: bit0 solid, bit1 floor, bit2 slope, bit3 hurts, bit4 bumpable, bit5 lava, bit6 pipe
            inc.Append(".define TILE_PROPS ");
            var props = new List<string>();
            for (int i = 0; i < 64; i++)
            {
                T t = (T)i;
                int p = 0;
                if (i <= (int)T.BigBlockBody)
                {
                    if (TileInfo.Solid(t)) p |= 1;
                    if (TileInfo.Floor(t)) p |= 2;
                    if (TileInfo.Slope(t)) p |= 4;
                    if (TileInfo.Hurts(t)) p |= 8;
                    if (TileInfo.Bumpable(t)) p |= 16;
                    if (TileInfo.Lava(t)) p |= 32;
                    if (TileInfo.Pipe(t)) p |= 64;
                }
                props.Add(p.ToString());
            }
            inc.AppendLine(string.Join(",", props));
            File.WriteAllText(Path.Combine(outDir, "levels.inc"), inc.ToString());
            return errors == 0 ? 0 : 1;
        }

        static string SymbolFallbacks(List<LevelDef> defs)
        {
            var sb = new StringBuilder();
            sb.AppendLine(".include \"themes.inc\"");
            sb.AppendLine(".include \"music.inc\"");
            var names = new SortedSet<string>();
            foreach (var th in Themes) names.Add("THEME_" + th.ToUpperInvariant());
            foreach (var d in defs) foreach (var a in d.Areas) names.Add("SONG_" + a.Music.ToUpperInvariant());
            names.Add("SONG_BOSS"); names.Add("SONG_BOWSER");
            foreach (var n in names) sb.AppendLine(".ifndef " + n + "\n" + n + " = 0\n.endif");
            return sb.ToString();
        }

        public static string Sym(string id) { return id.Replace('-', '_').ToLowerInvariant(); }

        // ------------------------------------------------------------------------------------------------ areas
        static void EmitArea(BankPacker packer, string name, AreaDef a, Tileset ts)
        {
            int w = a.W, h = a.H;
            var tiles = new byte[w * h];
            for (int i = 0; i < tiles.Length; i++) tiles[i] = (byte)a.Tiles[i];
            var gfx = ts.AreaGrid(a);
            var tz = new Blob(name + "_t"); tz.Bytes(Lz.Compress(tiles)); packer.Add(tz);
            var gz = new Blob(name + "_g"); gz.Bytes(Lz.Compress(gfx)); packer.Add(gz);

            var b = new Blob(name);
            b.Byte(w); b.Byte(h);
            b.Byte(Array.IndexOf(Themes, a.Theme));
            b.Raw("\t.byte THEME_" + a.Theme.ToUpperInvariant());
            b.Byte(a.Backdrop >= 0 ? 1 : 0);
            // boss rooms: the boss song is the area song, so its (slow) SPC upload happens under the area-load blank
            // instead of when the boss activates mid-gameplay (C# switches at activation)
            string mus = "SONG_" + a.Music.ToUpperInvariant();
            if (a.Spawns.Exists(s => s.Code == 'Y')) mus = "SONG_BOWSER";
            else if (a.Spawns.Exists(s => s.Code == 'Z' || s.Code == 'K')) mus = "SONG_BOSS";
            b.Raw("\t.byte " + mus);
            int sc = Array.IndexOf(Scrolls, a.Scroll); if (sc < 0) sc = 0;
            b.Byte(sc);
            b.Byte(a.AutoSpeed);
            b.Byte(a.WaterRow < 0 ? 0xFF : a.WaterRow);
            b.Byte(a.GoalX < 0 ? 0xFF : a.GoalX);
            b.Byte(a.GoalY < 0 ? 0 : a.GoalY);
            b.Byte(a.HasSlopes ? 1 : 0);
            b.Byte(a.Theme == "ice" ? 1 : 0);
            b.Word(a.Backdrop >= 0 ? SnesExport.Bgr555(a.Backdrop) : 0);   // bg_flat_color for bg= areas
            b.Far(name + "_t"); b.Far(name + "_g");
            // contents / var (sparse)
            var cont = new List<int>();
            for (int i = 0; i < w * h; i++) if (a.Contents[i] != Content.None) cont.Add(i);
            b.Word(cont.Count);
            foreach (int i in cont) { b.Word(i); b.Byte((int)a.Contents[i]); }
            var vars = new List<int>();
            for (int i = 0; i < w * h; i++) if (a.Var[i] != 0) vars.Add(i);
            b.Word(vars.Count);
            foreach (int i in vars) { b.Word(i); b.Byte(a.Var[i]); }
            // link markers
            var links = new List<int>();
            for (int i = 0; i < w * h; i++) if (a.Link[i] >= 0) links.Add(i);
            b.Byte(links.Count);
            foreach (int i in links) { b.Byte(i % w); b.Byte(i / w); b.Byte(a.Link[i]); }
            // spawns (sorted by x, then y, as the C# loader does)
            b.Word(a.Spawns.Count);
            foreach (var s in a.Spawns) { b.Byte(s.Code); b.Byte(s.X); b.Byte(s.Y); }
            packer.Add(b);
        }

        // ------------------------------------------------------------------------------------------------ font
        static byte[] FontTile(char c)
        {
            // 2bpp: color 1 = light upper rows, 2 = lower rows, 3 = 1-px drop shadow (down-right, down)
            var px = new int[64];
            var g = Font.Glyph(c);
            if (g != null)
            {
                for (int y = 0; y < 8; y++)
                    for (int x = 0; x < 8; x++)
                    {
                        if (g.P[y * 8 + x] == 0) continue;
                        int[,] sh = { { 1, 1 }, { 0, 1 } };
                        for (int k = 0; k < 2; k++)
                        {
                            int sx = x + sh[k, 0], sy = y + sh[k, 1];
                            if (sx < 8 && sy < 8 && px[sy * 8 + sx] == 0) px[sy * 8 + sx] = 3;
                        }
                    }
                for (int y = 0; y < 8; y++)
                    for (int x = 0; x < 8; x++)
                        if (g.P[y * 8 + x] != 0) px[y * 8 + x] = y < 4 ? 1 : 2;
            }
            var o = new byte[16];
            for (int y = 0; y < 8; y++)
            {
                int p0 = 0, p1 = 0;
                for (int x = 0; x < 8; x++)
                {
                    int v = px[y * 8 + x];
                    if ((v & 1) != 0) p0 |= 0x80 >> x;
                    if ((v & 2) != 0) p1 |= 0x80 >> x;
                }
                o[y * 2] = (byte)p0; o[y * 2 + 1] = (byte)p1;
            }
            return o;
        }

        // ================================================================================================ tilesets
        /// <summary>One layer of a 16x16 metatile image: an art image drawn with a palette (or a solid black fill).</summary>
        sealed class Layer
        {
            public string Img, PalName; public ushort[] Pal; public bool Fh, Fv, Black;
            public string Key { get { return Black ? "#black" : Img + ":" + PalName + ":" + (Fh ? 1 : 0) + (Fv ? 1 : 0); } }
        }

        sealed class Spec
        {
            public List<Layer> Layers = new List<Layer>();
            public bool Prio;
            public int Id = -1;              // metatile id
            public int AnimSlot = -1;
            public string Key
            {
                get
                {
                    var sb = new StringBuilder();
                    foreach (var l in Layers) sb.Append(l.Key).Append(';');
                    sb.Append(Prio ? "P" : "-");
                    return sb.ToString();
                }
            }
        }

        static readonly Dictionary<string, string> GroundSet = new Dictionary<string, string>
        {
            { "plains", "grass" }, { "jungle", "grass" }, { "desert", "sand" }, { "sea", "sand" }, { "sky", "cloud" }, { "ice", "snow" },
            { "underground", "rock" }, { "volcano", "rock" }, { "fortress", "stone" }, { "castle", "stone" }, { "machine", "metal" },
            { "airship", "wood" }, { "bonus", "wood" },
        };

        /// <summary>Animated images: base name -> (frame names, tick shift). Frame = (levelFrame >> shift) % count.</summary>
        static readonly Dictionary<string, KeyValuePair<string[], int>> Anims = new Dictionary<string, KeyValuePair<string[], int>>
        {
            { "qblock.1", new KeyValuePair<string[], int>(new[] { "qblock.1", "qblock.2", "qblock.3", "qblock.4" }, 3) },
            { "coin.1", new KeyValuePair<string[], int>(new[] { "coin.1", "coin.2", "coin.3", "coin.4" }, 3) },
            { "note.1", new KeyValuePair<string[], int>(new[] { "note.1", "note.2" }, 3) },
            { "muncher.1", new KeyValuePair<string[], int>(new[] { "muncher.1", "muncher.2" }, 3) },
            { "lava.top1", new KeyValuePair<string[], int>(new[] { "lava.top1", "lava.top2" }, 4) },
            { "water.top1", new KeyValuePair<string[], int>(new[] { "water.top1", "water.top2" }, 4) },
            { "conveyor.1", new KeyValuePair<string[], int>(new[] { "conveyor.1", "conveyor.2" }, 2) },
            { "torch.1", new KeyValuePair<string[], int>(new[] { "torch.1", "torch.2" }, 3) },
        };

        sealed class AnimSlot { public int Spec; public string Base; public int Count, Shift, ChrBase; public List<int[]> FrameTiles = new List<int[]>(); }

        sealed class Tileset
        {
            public readonly string Theme;
            readonly List<AreaDef> areas = new List<AreaDef>();
            readonly Dictionary<string, Spec> specs = new Dictionary<string, Spec>();
            readonly List<Spec> specList = new List<Spec>();
            readonly Dictionary<AreaDef, byte[]> grids = new Dictionary<AreaDef, byte[]>();
            readonly int[,] dyn = new int[4, 8];
            readonly List<AnimSlot> anims = new List<AnimSlot>();
            readonly List<byte[]> chr = new List<byte[]>();          // 4bpp index arrays (64) per CHR tile
            readonly Dictionary<string, int> chrIndex = new Dictionary<string, int>();
            readonly ushort[][] pals = new ushort[4][];
            readonly List<ushort[]> mtWords = new List<ushort[]>();
            public Tileset(string theme) { Theme = theme; Intern(new Spec()); }

            public void AddArea(AreaDef a) { areas.Add(a); }

            public string Summary() { return mtWords.Count + " metatiles, " + chr.Count + " CHR tiles, " + anims.Count + " animated"; }

            ushort[] ThemePal(string group, out string name)
            {
                string key = Theme + "." + group;
                if (Art.HasPal(key)) { name = key; return Art.Pal(key); }
                if (Art.HasPal("default." + group)) { name = "default." + group; return Art.Pal("default." + group); }
                name = "#fallback"; return Art.P(0x0F, 0x17, 0x27);
            }

            Layer L(string img, string group, bool fh = false, bool fv = false)
            {
                string pn; var p = ThemePal(group, out pn);
                return new Layer { Img = img, Pal = p, PalName = pn, Fh = fh, Fv = fv };
            }

            Layer LP(string img, string palName, bool fh = false)
            {
                return new Layer { Img = img, Pal = Art.Pal(palName), PalName = palName, Fh = fh };
            }

            Layer DecorLayer(string img)
            {
                string k1 = Theme + ".decor." + img, k2 = "decor." + img;
                if (Art.HasPal(k1)) return LP(img, k1);
                if (Art.HasPal(k2)) return LP(img, k2);
                return L(img, "decor");
            }

            int Intern(Spec s)
            {
                string k = s.Key;
                Spec e;
                if (specs.TryGetValue(k, out e)) return e.Id;
                s.Id = specList.Count;
                specs[k] = s; specList.Add(s);
                return s.Id;
            }

            // -------------------------------------------------------------- per-cell images (port of WorldRender)
            static T Get(AreaDef a, int x, int y) { return x < 0 || y < 0 || x >= a.W || y >= a.H ? T.Empty : a.Tiles[y * a.W + x]; }
            static T TileAt(AreaDef a, int tx, int ty)
            {
                if (tx < 0 || tx >= a.W) return ty < 0 ? T.Empty : T.Barrier;
                if (ty < 0 || ty >= a.H) return T.Empty;
                return a.Tiles[ty * a.W + tx];
            }
            static bool IsGround(AreaDef a, int tx, int ty)
            {
                if (tx < 0 || tx >= a.W) { T e = ty >= 0 && ty < a.H ? TileAt(a, Math.Max(0, Math.Min(a.W - 1, tx)), ty) : T.Empty; return e == T.Ground || TileInfo.Slope(e); }
                if (ty >= a.H) return true;
                if (ty < 0) return false;
                T t = a.Tiles[ty * a.W + tx];
                return t == T.Ground || TileInfo.Slope(t);
            }
            string GroundPiece(AreaDef a, int tx, int ty)
            {
                string set;
                if (!GroundSet.TryGetValue(Theme, out set)) set = "grass";
                bool up = IsGround(a, tx, ty - 1);
                T above = TileAt(a, tx, ty - 1);
                if (above == T.SlopeUp && Art.Has("ground." + set + ".sub")) return "ground." + set + ".sub";
                if (above == T.SlopeDown && Art.Has("ground." + set + ".sdb")) return "ground." + set + ".sdb";
                if (set == "rock" || set == "stone" || set == "metal" || set == "wood") return "ground." + set + (up ? ".c" : ".t");
                bool dn = IsGround(a, tx, ty + 1), lf = IsGround(a, tx - 1, ty), rt = IsGround(a, tx + 1, ty);
                string s;
                if (!up)
                {
                    bool wallL = lf && IsGround(a, tx - 1, ty - 1), wallR = rt && IsGround(a, tx + 1, ty - 1);
                    if (wallL && !wallR) s = "itl";
                    else if (wallR && !wallL) s = "itr";
                    else s = !lf && rt ? "tl" : !rt && lf ? "tr" : "t";
                }
                else if (!dn) s = !lf ? "bl" : !rt ? "br" : "b";
                else if (!lf) s = "l";
                else if (!rt) s = "r";
                else s = "c";
                return "ground." + set + "." + s;
            }
            static string BlockPiece(AreaDef a, int tx, int ty, byte color)
            {
                Func<int, int, bool> same = (x, y) => x >= 0 && y >= 0 && x < a.W && y < a.H && (a.Tiles[y * a.W + x] == T.BigBlock || a.Tiles[y * a.W + x] == T.BigBlockBody) && a.Var[y * a.W + x] == color;
                bool up = same(tx, ty - 1), dn = same(tx, ty + 1), lf = same(tx - 1, ty), rt = same(tx + 1, ty);
                string v = !up ? "t" : !dn ? "b" : "";
                string h = !lf ? "l" : !rt ? "r" : "";
                if (v == "" && h == "") return "block.c";
                return "block." + v + h;
            }

            /// <summary>The tile layer as World.DrawTileImage draws it at Frame 0 (animated images use frame 1).</summary>
            Layer TileLayer(AreaDef a, T t, int tx, int ty)
            {
                int W = a.W;
                switch (t)
                {
                    case T.Ground: return L(GroundPiece(a, tx, ty), "ground");
                    case T.Hard: return L("hard", "hard");
                    case T.Brick: return L("brick", "brick");
                    case T.QBlock: return L("qblock.1", "qblock");
                    case T.Used: return L("used", "used");
                    case T.Wood: return L("wood", "wood");
                    case T.Note: return L("note.1", "note");
                    case T.Ice: return L("ice", "ice");
                    case T.Muncher: return L("muncher.1", "muncher");
                    case T.Spike: return L("spike", "spike");
                    case T.Semi: { bool l = TileAt(a, tx - 1, ty) == T.Semi, r = TileAt(a, tx + 1, ty) == T.Semi; return L(!l ? "semi.l" : !r ? "semi.r" : "semi.c", "semi"); }
                    case T.Cloud: { bool l = TileAt(a, tx - 1, ty) == T.Cloud, r = TileAt(a, tx + 1, ty) == T.Cloud; return L(!l ? "cloud.l" : !r ? "cloud.r" : "cloud.c", "cloud"); }
                    case T.BigBlock:
                    case T.BigBlockBody: { byte c = a.Var[ty * W + tx]; return L(BlockPiece(a, tx, ty, c), "block" + Math.Max(1, Math.Min(4, (int)c))); }
                    case T.PipeTL: return L("pipe.tl", "pipe");
                    case T.PipeTR: return L("pipe.tr", "pipe");
                    case T.PipeL: return L("pipe.l", "pipe");
                    case T.PipeR: return L("pipe.r", "pipe");
                    case T.PipeBL: return L("pipe.bl", "pipe");
                    case T.PipeBR: return L("pipe.br", "pipe");
                    case T.HPipeMouthT: return L("hpipe.ml", "pipe", a.Var[ty * W + tx] == 1);
                    case T.HPipeMouthB: return L("hpipe.mlb", "pipe", ty > 0 && a.Var[(ty - 1) * W + tx] == 1);
                    case T.HPipeT: return L("hpipe.t", "pipe");
                    case T.HPipeB: return L("hpipe.b", "pipe");
                    case T.CannonTop: return L("cannon.top", "cannon");
                    case T.CannonMid: return L("cannon.mid", "cannon");
                    case T.CannonL: return L("cannon.top", "cannon");
                    case T.CannonR: return L("cannon.top", "cannon", true);
                    case T.Coin: return LP("coin.1", "coin");
                    case T.Vine: return L(TileAt(a, tx, ty - 1) == T.Vine ? "vine" : "vine.top", "vine");
                    case T.DoorTop: return L("door.top", "door");
                    case T.DoorBot: return L("door.bot", "door");
                    case T.LavaTop: return L("lava.top1", "lava");
                    case T.Lava: return L("lava", "lava");
                    case T.GoalFloor: return L("goal.floor", "goal");
                    case T.SlopeUp:
                    case T.SlopeDown:
                    {
                        string set;
                        if (!GroundSet.TryGetValue(Theme, out set)) set = "grass";
                        if (set == "cloud" || set == "metal" || set == "wood") set = "grass";
                        return L("ground." + set + (t == T.SlopeUp ? ".su" : ".sd"), "ground");
                    }
                    case T.ConveyorL: return L("conveyor.1", "conveyor", true);
                    case T.ConveyorR: return L("conveyor.1", "conveyor");
                }
                return null;
            }

            /// <summary>Background class of a cell: 0 sky, 1 water surface, 2 water, 3 dark goal backstage.</summary>
            public static int BgClass(AreaDef a, int x, int y)
            {
                if (a.WaterRow >= 0 && y >= a.WaterRow) return y == a.WaterRow && a.WaterRow > 0 ? 1 : 2;
                if (a.GoalX >= 0 && x >= a.GoalX - 2 && y >= a.GoalY - 12 && y < a.GoalY + 4) return 3;
                return 0;
            }

            List<Layer> BgLayers(int cls)
            {
                var r = new List<Layer>();
                if (cls == 3) r.Add(new Layer { Black = true });
                if (cls == 1) r.Add(L("water.top1", "water"));
                return r;
            }

            Spec CellSpec(AreaDef a, int x, int y, Dictionary<int, List<string>> decor)
            {
                var s = new Spec();
                int i = y * a.W + x;
                T t = a.Tiles[i];
                int goalPx = a.GoalX >= 0 ? (a.GoalX - 2) * 16 : int.MaxValue;
                bool back = a.GoalX >= 0 && x * 16 >= goalPx && y >= a.GoalY - 12 && y < a.GoalY + 4;
                if (back) s.Layers.Add(new Layer { Black = true });
                // water: only the surface row is BG1; the body is BG2's underwater gradient/layers (backgrounds module)
                if (a.WaterRow > 0 && y == a.WaterRow && (t == T.Empty || t == T.Coin))
                    s.Layers.Add(L("water.top1", "water"));
                List<string> dl;
                if (decor.TryGetValue(i, out dl) && x * 16 < goalPx)
                    foreach (var img in dl) s.Layers.Add(DecorLayer(img));
                if (t != T.Empty && t != T.Barrier && t != T.HiddenBlock)
                {
                    Layer tl = t == T.Ground && x * 16 >= goalPx ? L("goal.floor", "goal") : TileLayer(a, t, x, y);
                    if (tl != null) s.Layers.Add(tl);
                    s.Prio = TileInfo.Solid(t);
                }
                s.Layers.RemoveAll(l => !l.Black && !Art.Has(l.Img));
                if (s.Layers.Count == 0) s.Prio = false;
                return s;
            }

            public byte[] AreaGrid(AreaDef a) { return grids[a]; }

            public int Build()
            {
                int errs = 0;
                // cell specs for every area
                var cellSpec = new Dictionary<AreaDef, int[]>();
                foreach (var a in areas)
                {
                    var decor = new Dictionary<int, List<string>>();
                    foreach (var d in a.Decor)
                    {
                        if (d.X < 0 || d.Y < 0 || d.X >= a.W || d.Y >= a.H) continue;
                        int k = d.Y * a.W + d.X;
                        List<string> l;
                        if (!decor.TryGetValue(k, out l)) { l = new List<string>(); decor[k] = l; }
                        l.Add(d.Img);
                    }
                    var g = new int[a.W * a.H];
                    for (int y = 0; y < a.H; y++)
                        for (int x = 0; x < a.W; x++)
                            g[y * a.W + x] = Intern(CellSpec(a, x, y, decor));
                    cellSpec[a] = g;
                }
                // runtime table for tiles that change: [bg class][DYN_*]
                bool[] used = new bool[4];
                foreach (var a in areas) for (int y = 0; y < a.H; y++) for (int x = 0; x < a.W; x++) used[BgClass(a, x, y)] = true;
                var dummy = new AreaDef { W = 1, H = 1, Tiles = new T[1], Var = new byte[1], Contents = new Content[1] };
                for (int c = 0; c < 4; c++)
                    for (int k = 0; k < 8; k++)
                    {
                        if (!used[c]) { dyn[c, k] = dyn[0, k]; continue; }
                        var s = new Spec();
                        if (k <= 1) s.Layers.AddRange(BgLayers(c));
                        else if (c == 3) s.Layers.Add(new Layer { Black = true });
                        switch (k)
                        {
                            case 1: s.Layers.Add(LP("coin.1", "coin")); break;
                            case 2: s.Layers.Add(L("brick", "brick")); s.Prio = true; break;
                            case 3: s.Layers.Add(L("used", "used")); s.Prio = true; break;
                            case 4: s.Layers.Add(L("vine", "vine")); break;
                            case 5: s.Layers.Add(L("vine.top", "vine")); break;
                            case 6: s.Layers.Add(L("muncher.1", "muncher")); s.Prio = true; break;
                            case 7: s.Layers.Add(L("qblock.1", "qblock")); s.Prio = true; break;
                        }
                        s.Layers.RemoveAll(l => !l.Black && !Art.Has(l.Img));
                        dyn[c, k] = Intern(s);
                    }
                if (specList.Count > 256) { Console.WriteLine("  tileset " + Theme + ": " + specList.Count + " metatiles (max 256)"); errs++; }
                foreach (var a in areas)
                {
                    var g = cellSpec[a];
                    var b = new byte[g.Length];
                    for (int i = 0; i < g.Length; i++) b[i] = (byte)g[i];
                    grids[a] = b;
                }

                // ---- render every spec (all animation frames) into 16x16 BGR555 pixels (-1 = transparent)
                var frames = new List<List<int[]>>();   // per spec: list of frames
                for (int si = 0; si < specList.Count; si++)
                {
                    var s = specList[si];
                    string animBase = null;
                    foreach (var l in s.Layers) if (!l.Black && Anims.ContainsKey(l.Img)) { animBase = l.Img; break; }
                    var fl = new List<int[]>();
                    if (animBase == null) fl.Add(Render(s.Layers, null, null));
                    else
                    {
                        var an = Anims[animBase];
                        foreach (var fname in an.Key) fl.Add(Render(s.Layers, animBase, Art.Has(fname) ? fname : animBase));
                        var slot = new AnimSlot { Spec = si, Base = animBase, Count = an.Key.Length, Shift = an.Value };
                        s.AnimSlot = anims.Count; anims.Add(slot);
                    }
                    frames.Add(fl);
                }

                // ---- palette items: one per 8x8 tile position (animated: union over frames)
                var items = new List<Item>();
                var itemOf = new Dictionary<long, Item>();
                for (int si = 0; si < specList.Count; si++)
                    for (int q = 0; q < 4; q++)
                    {
                        var it = new Item();
                        foreach (var f in frames[si])
                            for (int y = 0; y < 8; y++)
                                for (int x = 0; x < 8; x++)
                                {
                                    int c = f[(y + (q >> 1) * 8) * 16 + x + (q & 1) * 8];
                                    if (c < 0) continue;
                                    int n; it.Hist.TryGetValue(c, out n); it.Hist[c] = n + 1;
                                }
                        items.Add(it);
                        itemOf[(long)si * 4 + q] = it;
                    }
                Quantize(items);
                for (int p = 0; p < 4; p++) pals[p] = new ushort[16];
                for (int p = 0; p < 4; p++) { int k = 1; foreach (var c in palSets[p]) pals[p][k++] = (ushort)c; }

                // ---- CHR: tile 0 blank, animated slots first (fixed tiles), then deduplicated static tiles
                chr.Add(new byte[64]);
                chrIndex[Convert.ToBase64String(new byte[64])] = 0;
                foreach (var slot in anims)
                {
                    slot.ChrBase = chr.Count;
                    for (int q = 0; q < 4; q++) chr.Add(null);
                }
                for (int si = 0; si < specList.Count; si++)
                {
                    var s = specList[si];
                    var words = new ushort[4];
                    for (int q = 0; q < 4; q++)
                    {
                        var it = itemOf[(long)si * 4 + q];
                        int pal = it.Pal;
                        if (s.AnimSlot >= 0)
                        {
                            var slot = anims[s.AnimSlot];
                            int tile = slot.ChrBase + q;
                            for (int f = 0; f < frames[si].Count; f++)
                            {
                                var idx = TileIndices(frames[si][f], q, pal);
                                if (f == 0) chr[tile] = idx;
                                if (slot.FrameTiles.Count <= f) slot.FrameTiles.Add(new int[4]);
                                slot.FrameTiles[f][q] = chr.Count; // placeholder: store frame tile data separately
                                frameData.Add(idx);
                                slot.FrameTiles[f][q] = frameData.Count - 1;
                            }
                            words[q] = (ushort)(tile | ((2 + pal) << 10) | (s.Prio ? 0x2000 : 0));
                        }
                        else
                        {
                            var idx = TileIndices(frames[si][0], q, pal);
                            bool blank = true; foreach (var v in idx) if (v != 0) { blank = false; break; }
                            if (blank) { words[q] = (ushort)((2 + pal) << 10 | (s.Prio ? 0x2000 : 0)); continue; }
                            int tile; bool fh, fv;
                            FindOrAdd(idx, out tile, out fh, out fv);
                            words[q] = (ushort)(tile | ((2 + pal) << 10) | (s.Prio ? 0x2000 : 0) | (fh ? 0x4000 : 0) | (fv ? 0x8000 : 0));
                        }
                    }
                    mtWords.Add(words);
                }
                if (chr.Count > 768) { Console.WriteLine("  tileset " + Theme + ": " + chr.Count + " CHR tiles (max 768)"); errs++; }
                return errs;
            }

            readonly List<byte[]> frameData = new List<byte[]>();

            void FindOrAdd(byte[] idx, out int tile, out bool fh, out bool fv)
            {
                for (int v = 0; v < 4; v++)
                {
                    bool h = (v & 1) != 0, vv = (v & 2) != 0;
                    var t = new byte[64];
                    for (int y = 0; y < 8; y++) for (int x = 0; x < 8; x++) t[y * 8 + x] = idx[(vv ? 7 - y : y) * 8 + (h ? 7 - x : x)];
                    int k;
                    if (chrIndex.TryGetValue(Convert.ToBase64String(t), out k)) { tile = k; fh = h; fv = vv; return; }
                }
                tile = chr.Count; fh = false; fv = false;
                chr.Add(idx);
                chrIndex[Convert.ToBase64String(idx)] = tile;
            }

            byte[] TileIndices(int[] px16, int q, int pal)
            {
                var o = new byte[64];
                for (int y = 0; y < 8; y++)
                    for (int x = 0; x < 8; x++)
                    {
                        int c = px16[(y + (q >> 1) * 8) * 16 + x + (q & 1) * 8];
                        o[y * 8 + x] = c < 0 ? (byte)0 : (byte)Nearest(pal, c);
                    }
                return o;
            }

            int Nearest(int pal, int c)
            {
                int best = 1, bd = int.MaxValue;
                for (int k = 1; k < 16; k++)
                {
                    if (k > palSets[pal].Count) break;
                    int d = Dist(pals[pal][k], c);
                    if (d < bd) { bd = d; best = k; }
                }
                return best;
            }

            static int[] Render(List<Layer> layers, string animBase, string animFrame)
            {
                var o = new int[256];
                for (int i = 0; i < 256; i++) o[i] = -1;
                foreach (var l in layers)
                {
                    if (l.Black) { for (int i = 0; i < 256; i++) o[i] = 0; continue; }
                    string name = animBase != null && l.Img == animBase ? animFrame : l.Img;
                    var img = Art.Get(name);
                    int last = l.Pal.Length - 1;
                    for (int y = 0; y < 16 && y < img.H; y++)
                        for (int x = 0; x < 16 && x < img.W; x++)
                        {
                            int sx = l.Fh ? img.W - 1 - x : x, sy = l.Fv ? img.H - 1 - y : y;
                            if (sx < 0 || sy < 0 || sx >= img.W || sy >= img.H) continue;
                            int v = img.P[sy * img.W + sx];
                            if (v == 0) continue;
                            int ci = l.Pal[v <= last ? v : last];
                            int rgb = NesPalette.RgbOf(ci);
                            o[y * 16 + x] = ((rgb >> 19) & 31) | (((rgb >> 11) & 31) << 5) | (((rgb >> 3) & 31) << 10);
                        }
                }
                return o;
            }

            // -------------------------------------------------------------- palette clustering: 4 palettes x 15 colors
            sealed class Item { public Dictionary<int, int> Hist = new Dictionary<int, int>(); public int Pal; }
            readonly List<int>[] palSets = new List<int>[4];

            static int Dist(int a, int b)
            {
                int dr = (a & 31) - (b & 31), dg = ((a >> 5) & 31) - ((b >> 5) & 31), db = ((a >> 10) & 31) - ((b >> 10) & 31);
                return 2 * dr * dr + 4 * dg * dg + 3 * db * db;
            }

            void Quantize(List<Item> items)
            {
                var sets = new HashSet<int>[4];
                for (int p = 0; p < 4; p++) sets[p] = new HashSet<int>();
                var order = new List<Item>(items);
                order.Sort((a, b) => b.Hist.Count.CompareTo(a.Hist.Count));
                foreach (var it in order)
                {
                    if (it.Hist.Count == 0) { it.Pal = 0; continue; }
                    int best = -1, bestNew = int.MaxValue, bestSize = int.MaxValue;
                    for (int p = 0; p < 4; p++)
                    {
                        int nw = 0; foreach (var c in it.Hist.Keys) if (!sets[p].Contains(c)) nw++;
                        if (sets[p].Count + nw > 15) continue;
                        if (nw < bestNew || nw == bestNew && sets[p].Count > bestSize) { best = p; bestNew = nw; bestSize = sets[p].Count; }
                    }
                    if (best < 0)
                    {
                        long bc = long.MaxValue;
                        for (int p = 0; p < 4; p++)
                        {
                            long cost = 0;
                            foreach (var kv in it.Hist)
                            {
                                if (sets[p].Contains(kv.Key)) continue;
                                int md = int.MaxValue; foreach (var c in sets[p]) md = Math.Min(md, Dist(c, kv.Key));
                                cost += (long)kv.Value * (md == int.MaxValue ? 0 : md);
                            }
                            if (cost < bc) { bc = cost; best = p; }
                        }
                    }
                    it.Pal = best;
                    foreach (var c in it.Hist.Keys) sets[best].Add(c);
                }
                // reduce overflowing palettes by merging the closest pair (keep the more used color)
                for (int p = 0; p < 4; p++)
                {
                    var wgt = new Dictionary<int, long>();
                    foreach (var it in items) if (it.Pal == p) foreach (var kv in it.Hist) { long n; wgt.TryGetValue(kv.Key, out n); wgt[kv.Key] = n + kv.Value; }
                    var cols = new List<int>(wgt.Keys);
                    while (cols.Count > 15)
                    {
                        int ba = 0, bb = 1; long bd = long.MaxValue;
                        for (int i = 0; i < cols.Count; i++)
                            for (int j = i + 1; j < cols.Count; j++)
                            {
                                long d = (long)Dist(cols[i], cols[j]) * Math.Min(wgt[cols[i]], wgt[cols[j]]);
                                if (d < bd) { bd = d; ba = i; bb = j; }
                            }
                        int keep = wgt[cols[ba]] >= wgt[cols[bb]] ? ba : bb, drop = keep == ba ? bb : ba;
                        wgt[cols[keep]] += wgt[cols[drop]];
                        cols.RemoveAt(drop);
                    }
                    cols.Sort((a, b) => Lum(a).CompareTo(Lum(b)));
                    palSets[p] = cols;
                }
                // tiles whose palette ended up empty-ish still map to nearest; refine: each item to its best palette
                for (int p = 0; p < 4; p++) { pals[p] = new ushort[16]; int k = 1; foreach (var c in palSets[p]) pals[p][k++] = (ushort)c; }
                foreach (var it in items)
                {
                    if (it.Hist.Count == 0) continue;
                    long bestE = long.MaxValue; int bp = it.Pal;
                    for (int p = 0; p < 4; p++)
                    {
                        if (palSets[p].Count == 0) continue;
                        long e = 0;
                        foreach (var kv in it.Hist) { int md = int.MaxValue; foreach (var c in palSets[p]) md = Math.Min(md, Dist(c, kv.Key)); e += (long)md * kv.Value; }
                        if (e < bestE || e == bestE && p == it.Pal) { bestE = e; bp = p; }
                    }
                    it.Pal = bp;
                }
            }

            static int Lum(int c) { return (c & 31) * 3 + ((c >> 5) & 31) * 6 + ((c >> 10) & 31); }

            // -------------------------------------------------------------- output
            public void Emit(BankPacker packer, int themeIndex)
            {
                string n = "ts_" + Theme;
                // CHR (may be up to 24 KB: its own blob, split in two if > 16 KB so blobs pack well)
                var chrBytes = new List<byte>();
                foreach (var t in chr) chrBytes.AddRange(Planar(t ?? new byte[64]));
                var cb = new Blob(n + "_chr"); cb.Bytes(chrBytes.ToArray()); packer.Add(cb);
                var mt = new Blob(n + "_mt");
                foreach (var w in mtWords) foreach (var x in w) mt.Word(x);
                packer.Add(mt);
                var an = new Blob(n + "_anim");
                foreach (var s in anims)
                    for (int f = 0; f < s.Count; f++)
                        for (int q = 0; q < 4; q++) an.Bytes(Planar(frameData[s.FrameTiles[f][q]]));
                if (anims.Count > 0) packer.Add(an);
                var h = new Blob(n);
                h.Far(n + "_chr"); h.Word(chrBytes.Count);
                h.Far(n + "_mt"); h.Word(mtWords.Count);
                for (int p = 0; p < 4; p++) for (int k = 0; k < 16; k++) h.Word(pals[p][k]);
                for (int c = 0; c < 4; c++) for (int k = 0; k < 8; k++) h.Byte(dyn[c, k]);
                h.Byte(anims.Count);
                int off = 0;
                foreach (var s in anims)
                {
                    h.Word(s.ChrBase * 16);        // VRAM word address of the slot's 4 tiles
                    h.Byte(s.Count); h.Byte(s.Shift);
                    if (anims.Count > 0) h.Raw("\t.faraddr " + n + "_anim+" + off);
                    off += s.Count * 128;
                }
                packer.Add(h);
            }

            static byte[] Planar(byte[] idx)
            {
                var o = new byte[32];
                for (int y = 0; y < 8; y++)
                {
                    int b0 = 0, b1 = 0, b2 = 0, b3 = 0;
                    for (int x = 0; x < 8; x++)
                    {
                        int v = idx[y * 8 + x], m = 0x80 >> x;
                        if ((v & 1) != 0) b0 |= m; if ((v & 2) != 0) b1 |= m; if ((v & 4) != 0) b2 |= m; if ((v & 8) != 0) b3 |= m;
                    }
                    o[y * 2] = (byte)b0; o[y * 2 + 1] = (byte)b1; o[16 + y * 2] = (byte)b2; o[16 + y * 2 + 1] = (byte)b3;
                }
                return o;
            }
        }

        // ================================================================================================ output helpers
        /// <summary>A labelled chunk of ROM data that must not cross a 32 KB LoROM bank.</summary>
        public sealed class Blob
        {
            public readonly string Name;
            public int Size;
            readonly StringBuilder sb = new StringBuilder();
            readonly List<byte> pending = new List<byte>();
            public Blob(string name) { Name = name; }
            void Flush()
            {
                for (int i = 0; i < pending.Count; i += 32)
                {
                    sb.Append("\t.byte ");
                    for (int k = i; k < Math.Min(pending.Count, i + 32); k++) { if (k > i) sb.Append(','); sb.Append(pending[k]); }
                    sb.Append('\n');
                }
                pending.Clear();
            }
            public void Byte(int v) { pending.Add((byte)v); Size++; }
            public void Bytes(byte[] v) { pending.AddRange(v); Size += v.Length; }
            public void Word(int v) { Byte(v & 255); Byte((v >> 8) & 255); }
            public void Far(string label) { Flush(); sb.Append("\t.faraddr " + label + "\n"); Size += 3; }
            /// <summary>Raw line; must be exactly one byte unless it is a .faraddr (3 bytes).</summary>
            public void Raw(string line) { Flush(); sb.Append(line + "\n"); Size += line.Contains(".faraddr") ? 3 : 1; }
            public string Text { get { Flush(); return sb.ToString(); } }
        }

        public sealed class BankPacker
        {
            readonly List<Blob> blobs = new List<Blob>();
            public void Add(Blob b) { blobs.Add(b); }
            public string Emit(string[] exports)
            {
                // first-fit decreasing into BANK40..BANK55
                var sorted = new List<Blob>(blobs);
                sorted.Sort((a, b) => b.Size.CompareTo(a.Size));
                int nb = LastBank - FirstBank + 1;
                var fill = new int[nb];
                var content = new List<Blob>[nb];
                for (int i = 0; i < nb; i++) content[i] = new List<Blob>();
                foreach (var b in sorted)
                {
                    int k = -1;
                    for (int i = 0; i < nb; i++) if (fill[i] + b.Size <= 0x8000) { k = i; break; }
                    if (k < 0) return null;
                    fill[k] += b.Size; content[k].Add(b);
                }
                var sb = new StringBuilder();
                foreach (var e in exports) sb.Append(".export " + e + "\n");
                int total = 0;
                for (int i = 0; i < nb; i++)
                {
                    if (content[i].Count == 0) continue;
                    sb.Append("\n.segment \"BANK" + (FirstBank + i) + "\"\n");
                    foreach (var b in content[i]) { sb.Append(b.Name + ":\n"); sb.Append(b.Text); }
                    total += fill[i];
                }
                Console.WriteLine("  levels+tiles: " + total / 1024 + " KB in banks " + FirstBank + "-" + LastBank);
                return sb.ToString();
            }
        }

        /// <summary>
        /// Byte-oriented LZ77: control byte c &lt; $80 = (c+1) literal bytes follow; c &gt;= $80 = copy (c&amp;$7F)+3 bytes
        /// from 'distance' bytes back (16-bit little-endian distance follows). The decoder knows the output size.
        /// </summary>
        public static class Lz
        {
            public static byte[] Compress(byte[] src)
            {
                var o = new List<byte>();
                var lit = new List<byte>();
                var head = new Dictionary<int, List<int>>();
                int i = 0;
                Action flush = () =>
                {
                    for (int k = 0; k < lit.Count; k += 128)
                    {
                        int n = Math.Min(128, lit.Count - k);
                        o.Add((byte)(n - 1));
                        for (int j = 0; j < n; j++) o.Add(lit[k + j]);
                    }
                    lit.Clear();
                };
                while (i < src.Length)
                {
                    int bestLen = 0, bestDist = 0;
                    if (i + 3 <= src.Length)
                    {
                        int key = src[i] | src[i + 1] << 8 | src[i + 2] << 16;
                        List<int> cand;
                        if (head.TryGetValue(key, out cand))
                        {
                            for (int c = cand.Count - 1; c >= 0 && c >= cand.Count - 256; c--)
                            {
                                int p = cand[c];
                                int len = 0;
                                while (i + len < src.Length && len < 130 && src[p + len] == src[i + len]) len++;
                                if (len > bestLen) { bestLen = len; bestDist = i - p; if (len == 130) break; }
                            }
                        }
                    }
                    int step = bestLen >= 3 ? bestLen : 1;
                    if (bestLen >= 3)
                    {
                        flush();
                        o.Add((byte)(0x80 | (bestLen - 3)));
                        o.Add((byte)(bestDist & 255)); o.Add((byte)(bestDist >> 8));
                    }
                    else lit.Add(src[i]);
                    for (int k = 0; k < step; k++)
                    {
                        int j = i + k;
                        if (j + 3 <= src.Length)
                        {
                            int key = src[j] | src[j + 1] << 8 | src[j + 2] << 16;
                            List<int> l;
                            if (!head.TryGetValue(key, out l)) { l = new List<int>(); head[key] = l; }
                            l.Add(j);
                        }
                    }
                    i += step;
                }
                flush();
                // self-check
                var d = Decompress(o.ToArray(), src.Length);
                for (int k = 0; k < src.Length; k++) if (d[k] != src[k]) throw new Exception("LZ self-check failed");
                return o.ToArray();
            }

            public static byte[] Decompress(byte[] z, int n)
            {
                var o = new byte[n];
                int i = 0, j = 0;
                while (j < n)
                {
                    int c = z[i++];
                    if (c < 0x80) { for (int k = 0; k <= c; k++) o[j++] = z[i++]; }
                    else { int len = (c & 0x7F) + 3, dist = z[i] | z[i + 1] << 8; i += 2; for (int k = 0; k < len; k++, j++) o[j] = o[j - dist]; }
                }
                return o;
            }
        }
    }
}
