using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Text;
using SMB4.Engine;
using SMB4.Game;

namespace SMB4.Tools
{
    /// <summary>
    /// SNES backgrounds converter (owner: backgrounds agent; runtime = snes/src/bg.s, docs = snes/BACKGROUNDS.md).
    /// Per theme and water variant ("dry" = para.THEME.1-4, "wet" = para.THEME.w1-4 only, "mix" = both) the parallax
    /// layers are cut into horizontal bands and stored on ONE BG2 layer: CHR ≤ 256 4bpp tiles (VRAM $3000), a 32x64
    /// tilemap (VRAM $4800, 256 px wide so every layer wraps seamlessly), palettes 6-7 (30 colors, merged/quantized).
    /// Each band ("segment") is a run of local rows of one layer; at run time bg.s paints the segments per scanline
    /// (margin blocks first, then the bands chosen for the floor camera, nearest layer last = wins) and builds the
    /// HDMA table that gives every band its own BG2 scroll (C# DrawParallax formulas). Which layer owns which rows is
    /// chosen from the opacity of each layer row ("nearest opaque layer wins"), simulated over every camera height
    /// the areas of that theme can reach so rows revealed by vertical parallax are stored too (budget permitting).
    /// Blob layout = BGV_* offsets below (mirrored in bg.s).
    /// </summary>
    public static partial class SnesExport
    {
        public static readonly string[] BgThemeNames = { "plains", "underground", "desert", "sea", "jungle", "sky", "ice", "machine", "volcano", "fortress", "castle", "airship", "bonus" };

        // ---- blob layout (keep in sync with bg.s) ----
        const int BGV_NLAYERS = 0, BGV_NSEG = 1, BGV_CHRBYTES = 2, BGV_TROW = 4, BGV_TLEN = 6, BGV_NDRY = 8, BGV_NWET = 9,
                  BGV_DRYSTART = 10, BGV_DRYCOL = 26, BGV_WETSTART = 58, BGV_WETCOL = 74, BGV_LNUM = 106, BGV_LBASE = 114,
                  BGV_SLAYER = 130, BGV_SFLAGS = 162, BGV_SR0 = 194, BGV_SR1 = 258, BGV_SVBASE = 322, BGV_SFILL = 386,
                  BGV_NFILL = 450, BGV_HDR = 452, BGV_FILL = 452, BGV_PAL = 452 + 384, BGV_MAP = 452 + 384 + 64,
                  BGV_CHR = 452 + 384 + 64 + 4096;
        const int MaxSeg = 32, MaxLayers = 8, MapRows = 64;

        sealed class BgLayer
        {
            public string Name; public Img Img; public int[] Rgb; public int Num, Base, Idx; public bool Wet;
            public double[] Cov; public int Group; public int[] SlotMap; public long[] SlotCount;
            public double[] RowWeight; public bool[] Owned; public int[] Pix; public int[] Fill;
        }
        sealed class BgCfg { public int D, WaterY, Weight; }
        sealed class BgSeg { public int Layer, R0, R1, VBase, FillIdx = 0xFFFF; public bool Wet; }
        sealed class BgTile { public byte[] P; public int Group; public long Count; public int MergedInto = -1; public int MergeFlip; }

        static int ExportBackgrounds(string outDir)
        {
            var inc = new StringBuilder();
            inc.Append("; generated by smb4tools snes-export (SnesBackgrounds.cs) - theme ids for bg_load\n");
            for (int i = 0; i < BgThemeNames.Length; i++) inc.Append("THEME_" + BgThemeNames[i].ToUpperInvariant() + " = " + i + "\n");
            inc.Append("THEME_COUNT = " + BgThemeNames.Length + "\n");
            File.WriteAllText(Path.Combine(outDir, "themes.inc"), inc.ToString());

            // areas per theme (flat bg= areas never show parallax)
            var areas = new Dictionary<string, List<AreaDef>>();
            foreach (var t in BgThemeNames) areas[t] = new List<AreaDef>();
            foreach (var path in Data.List("levels/"))
            {
                if (!path.EndsWith(".lvl", StringComparison.OrdinalIgnoreCase)) continue;
                string id = Path.GetFileNameWithoutExtension(path);
                if (id.StartsWith("_")) continue;
                var def = LevelLoader.Load(id);
                if (def == null) continue;
                foreach (var a in def.Areas)
                    if (a.Backdrop < 0 && areas.ContainsKey(a.Theme)) areas[a.Theme].Add(a);
            }

            string preview = Environment.GetEnvironmentVariable("SMB4_BGPREVIEW");
            var blobs = new List<KeyValuePair<string, byte[]>>();
            var dir = new string[3, BgThemeNames.Length];
            var report = new StringBuilder();
            for (int ti = 0; ti < BgThemeNames.Length; ti++)
            {
                string th = BgThemeNames[ti];
                bool hasWet = false;
                for (int L = 1; L <= 4; L++) if (Art.Has("para." + th + ".w" + L)) hasWet = true;
                var dry = new List<AreaDef>(); var wet = new List<AreaDef>(); var mix = new List<AreaDef>();
                foreach (var a in areas[th])
                {
                    if (a.WaterRow < 0 || !hasWet) dry.Add(a);
                    else if (a.WaterRow == 0) wet.Add(a);
                    else mix.Add(a);
                }
                string[] kinds = { "dry", "wet", "mix" };
                var lists = new[] { dry, wet, mix };
                for (int k = 0; k < 3; k++)
                {
                    if (k > 0 && lists[k].Count == 0) continue;
                    string name = th + "_" + kinds[k];
                    string rep;
                    byte[] blob = BuildBgVariant(th, k, lists[k], preview, out rep);
                    report.Append("  bg " + name + ": " + rep + "\n");
                    blobs.Add(new KeyValuePair<string, byte[]>(name, blob));
                    File.WriteAllBytes(Path.Combine(outDir, "bg_" + name + ".bin"), blob);
                    dir[k, ti] = "bgv_" + name;
                }
            }
            Console.Write(report.ToString());

            // pack blobs into banks BANK52..BANK63 (two per bank typically; a blob never crosses a bank)
            var s = new StringBuilder();
            s.Append("; generated by smb4tools snes-export (SnesBackgrounds.cs) - parallax/gradient data per theme variant\n");
            s.Append(".export bg_dir_dry, bg_dir_wet, bg_dir_mix\n");
            int bank = 52, used = 0;
            s.Append(".segment \"BANK52\"\n");
            foreach (var kv in blobs)
            {
                if (used + kv.Value.Length > 0x8000)
                {
                    bank++; used = 0;
                    if (bank > 63) throw new Exception("backgrounds: out of banks (BANK52-63)");
                    s.Append(".segment \"BANK" + bank + "\"\n");
                }
                s.Append("bgv_" + kv.Key + ": .incbin \"bg_" + kv.Key + ".bin\"\n");
                used += kv.Value.Length;
            }
            s.Append(".segment \"CODE5\"\n");
            string[] dn = { "bg_dir_dry", "bg_dir_wet", "bg_dir_mix" };
            for (int k = 0; k < 3; k++)
            {
                s.Append(dn[k] + ":");
                for (int ti = 0; ti < BgThemeNames.Length; ti++)
                    s.Append((ti == 0 ? " .faraddr " : ", ") + (dir[k, ti] ?? "0"));
                s.Append("\n");
            }
            File.WriteAllText(Path.Combine(outDir, "bg_themes.s"), s.ToString());
            Console.WriteLine("  backgrounds: " + blobs.Count + " variants in banks 52-" + bank);
            return 0;
        }

        static int[] BgPalRgb(string name)
        {
            var pal = Art.HasPal(name) ? Art.Pal(name) : Art.PreviewPalFor(name);
            var rgb = new int[16];
            for (int i = 1; i < 16; i++) rgb[i] = i < pal.Length ? NesPalette.RgbOf(pal[i]) : 0;
            return rgb;
        }

        /// <summary>24-bit RGB -> BGR555: of the 8 floor/ceil channel combinations, the one closest in luma with the
        /// chroma error weighted up (keeps dark near-greys neutral instead of tinting them red/green).</summary>
        static int Rgb555(int rgb)
        {
            int r = (rgb >> 16) & 255, g = (rgb >> 8) & 255, b = rgb & 255;
            int best = 0; double be = double.MaxValue;
            for (int k = 0; k < 8; k++)
            {
                int r5 = Math.Min(31, r * 31 / 255 + (k & 1)), g5 = Math.Min(31, g * 31 / 255 + ((k >> 1) & 1)), b5 = Math.Min(31, b * 31 / 255 + ((k >> 2) & 1));
                int e = Exp555(r5 | (g5 << 5) | (b5 << 10));
                double dr = ((e >> 16) & 255) - r, dg = ((e >> 8) & 255) - g, db = (e & 255) - b;
                double dy = 0.299 * dr + 0.587 * dg + 0.114 * db;
                double err = dy * dy * 4 + ((dr - dy) * (dr - dy) + (dg - dy) * (dg - dy) + (db - dy) * (db - dy)) * 3;
                if (err < be) { be = err; best = r5 | (g5 << 5) | (b5 << 10); }
            }
            return best;
        }

        /// <summary>BGR555 -> 24-bit RGB as the PPU/Mesen shows it.</summary>
        static int Exp555(int c)
        {
            int r = c & 31, g = (c >> 5) & 31, b = (c >> 10) & 31;
            return (((r << 3) | (r >> 2)) << 16) | (((g << 3) | (g >> 2)) << 8) | ((b << 3) | (b >> 2));
        }

        static List<BgLayer> BgLayers(string th, bool wet)
        {
            var list = new List<BgLayer>();
            for (int L = 1; L <= 4; L++)
            {
                string name = "para." + th + (wet ? ".w" : ".") + L;
                if (!Art.Has(name)) continue;
                var img = Art.Get(name);
                if (256 % img.W != 0) throw new Exception(name + ": width must divide 256");
                if (img.W != 256)
                {   // tile horizontally to 256 so the 32-column map wraps like the C# repeat
                    var w = new Img(256, img.H);
                    for (int y = 0; y < img.H; y++) for (int x = 0; x < 256; x++) w.P[y * 256 + x] = img.P[y * img.W + x % img.W];
                    img = w;
                }
                int extraY = Art.HasPal(name + ".y") ? Art.Pal(name + ".y")[1] : 0;
                list.Add(new BgLayer { Name = name, Img = new Img(256, img.H, (byte[])img.P.Clone()), Rgb = BgPalRgb(name), Num = L, Base = 192 - img.H + extraY, Wet = wet });
            }
            // Bake the farther layers' silhouettes into the transparent pixels of each nearer layer (floor-camera
            // alignment). The ROM shows one layer per scanline, so a near layer's band used to cut the far layer's
            // tree tops / hills off flat. Far content inside a near band now scrolls at the near layer's rate.
            for (int i = 1; i < list.Count; i++)
            {
                var N = list[i]; int used = 1;
                foreach (var b in N.Img.P) if (b + 1 > used) used = b + 1;
                for (int y = 0; y < N.Img.H; y++)
                {
                    int sy = N.Base + y;
                    for (int x = 0; x < 256; x++)
                    {
                        if (N.Img.P[y * 256 + x] != 0) continue;
                        int c = -1;
                        for (int j = i - 1; j >= 0 && c < 0; j--)
                        {
                            var F = list[j]; int fy = sy - F.Base;
                            if (fy < 0 || fy >= F.Img.H) continue;
                            int fp = F.Img.P[fy * 256 + x];
                            if (fp != 0) c = F.Rgb[fp];
                        }
                        if (c < 0) continue;
                        int slot = -1;
                        for (int s = 1; s < used; s++) if (N.Rgb[s] == c) { slot = s; break; }
                        if (slot < 0 && used < 16) { slot = used++; N.Rgb[slot] = c; }
                        if (slot < 0)
                        {
                            double bd = double.MaxValue;
                            for (int s = 1; s < used; s++) { double d = ColDist(N.Rgb[s], c); if (d < bd) { bd = d; slot = s; } }
                        }
                        N.Img.P[y * 256 + x] = (byte)slot;
                    }
                }
            }
            foreach (var ly in list)
            {
                var img = ly.Img;
                ly.Cov = new double[img.H];
                ly.SlotCount = new long[16];
                for (int y = 0; y < img.H; y++)
                {
                    int n = 0;
                    for (int x = 0; x < 256; x++) { int p = img.P[y * 256 + x]; if (p != 0) { n++; ly.SlotCount[p]++; } }
                    ly.Cov[y] = n / 256.0;
                }
                ly.RowWeight = new double[img.H]; ly.Owned = new bool[img.H]; ly.Fill = new int[img.H];
                ly.Pix = new int[256 * img.H];
                for (int i = 0; i < ly.Pix.Length; i++) ly.Pix[i] = img.P[i] == 0 ? -1 : ly.Rgb[img.P[i]];
            }
            return list;
        }

        static int BgHx(int camX, int num) { return (((camX & 0x7FF) * num) >> 3) & 255; }

        /// <summary>
        /// Which layer should own screen row y (layers ordered far to near), -1 = none: the one whose SNES rendering
        /// (its own pixels, holes filled with one flat backdrop color = the mean of what the holes should show) is
        /// closest to the true composite (nearest opaque layer, else the gradient), summed over the given camera x.
        /// </summary>
        static int BgChooseErr(List<BgLayer> g, int y, int d, int[] camXs, int grad, out int fill, double[] errs = null, int[] fillsOut = null)
        {
            int n = g.Count, ns = camXs.Length, np = ns * 256;
            fill = grad;
            var rows = new int[n]; var hx = new int[n * ns];
            bool any = false;
            for (int i = 0; i < n; i++)
            {
                rows[i] = y - (g[i].Base + d * g[i].Num / 16);
                if (rows[i] >= 0 && rows[i] < g[i].Img.H) any = true; else rows[i] = -1;
                for (int s = 0; s < ns; s++) hx[i * ns + s] = BgHx(camXs[s], g[i].Num);
            }
            if (!any) return -1;
            var truth = new int[np];
            for (int s = 0; s < ns; s++)
                for (int x = 0; x < 256; x++)
                {
                    int t = grad;
                    for (int i = n - 1; i >= 0; i--)
                    {
                        if (rows[i] < 0) continue;
                        int p = g[i].Pix[rows[i] * 256 + ((x + hx[i * ns + s]) & 255)];
                        if (p >= 0) { t = p; break; }
                    }
                    truth[s * 256 + x] = t;
                }
            double best = 0; int bi = -1;
            for (int k = 0; k < np; k++) best += ColDist(truth[k], grad);
            if (errs != null) { errs[0] = best; for (int i = 0; i < n; i++) errs[i + 1] = double.MaxValue; }
            for (int i = 0; i < n; i++)
            {
                if (rows[i] < 0) continue;
                var pix = g[i].Pix; int ro = rows[i] * 256;
                long sr = 0, sg = 0, sb = 0; int nh = 0;
                for (int s = 0; s < ns; s++)
                    for (int x = 0; x < 256; x++)
                        if (pix[ro + ((x + hx[i * ns + s]) & 255)] < 0)
                        { int t = truth[s * 256 + x]; sr += (t >> 16) & 255; sg += (t >> 8) & 255; sb += t & 255; nh++; }
                int f = nh == 0 ? grad : (int)(((sr + nh / 2) / nh) << 16 | ((sg + nh / 2) / nh) << 8 | ((sb + nh / 2) / nh));
                f = Exp555(Rgb555(f));
                double e = 0;
                for (int s = 0; s < ns && (e < best || errs != null); s++)
                    for (int x = 0; x < 256; x++)
                    {
                        int p = pix[ro + ((x + hx[i * ns + s]) & 255)];
                        e += ColDist(p >= 0 ? p : f, truth[s * 256 + x]);
                    }
                if (errs != null) { errs[i + 1] = e; fillsOut[i + 1] = f; }
                if (e < best) { best = e; bi = i; fill = f; }
            }
            return bi;
        }

        static byte[] BuildBgVariant(string th, int kind, List<AreaDef> areas, string preview, out string rep)
        {
            var dry = kind == 1 ? new List<BgLayer>() : BgLayers(th, false);
            var wet = kind == 0 ? new List<BgLayer>() : BgLayers(th, true);
            var all = new List<BgLayer>(); all.AddRange(dry); all.AddRange(wet);
            if (all.Count > MaxLayers) throw new Exception(th + ": too many layers");
            for (int i = 0; i < all.Count; i++) all[i].Idx = i;

            // ---- camera configurations the areas can reach (weight 100 = floor/lock camera, 1 = elsewhere) ----
            var cfgs = new Dictionary<long, BgCfg>();
            Action<int, int, int> addCfg = (d, wy, wgt) =>
            {
                long key = (long)d * 1000 + wy;
                BgCfg c;
                if (!cfgs.TryGetValue(key, out c)) { c = new BgCfg { D = d, WaterY = wy }; cfgs[key] = c; }
                c.Weight += wgt;
            };
            foreach (var a in areas)
            {
                int maxY = a.H * 16 - 192, floor = Math.Max(0, maxY);
                int waterPx = a.WaterRow < 0 ? -1 : a.WaterRow * 16 + (a.WaterRow > 0 ? 16 : 0);
                bool lockd = a.Scroll == "lock" || maxY <= 0;
                int minCam = lockd ? maxY : Math.Max(Math.Min(0, maxY), -128);
                for (int cy = maxY; cy >= minCam; cy -= 4)
                {
                    int wy = waterPx < 0 ? 192 : Math.Max(0, Math.Min(192, waterPx - cy));
                    addCfg(Math.Min(2047, floor - cy), wy, cy == maxY ? 100 : 1);
                }
            }
            if (cfgs.Count == 0)
            {
                int wy0 = kind == 0 ? 192 : kind == 1 ? 0 : 120;
                addCfg(0, wy0, 100);
                for (int d = 4; d <= 128; d += 4) addCfg(d, wy0, 1);
            }
            BgCfg refc = null;
            foreach (var c in cfgs.Values) if (refc == null || c.Weight > refc.Weight) refc = c;

            // ---- gradients (per screen row, as the PPU shows them) ----
            var dg = BgDryGradient(th);
            var wg = BgWetGradient(th);
            var dryRow = new int[192]; var wetRow = new int[192];
            for (int y = 0; y < 192; y++)
            {
                for (int k = 0; k < dg.Length; k++) if (192 * k / dg.Length <= y) dryRow[y] = Exp555(dg[k]);
                for (int k = 0; k < wg.Length; k++) if (192 * k / wg.Length <= y) wetRow[y] = Exp555(wg[k]);
            }

            // ---- owned rows + hole fill colors (reference = floor camera), row weights from all configurations ----
            int[] refX = { 0, 173, 411, 777 }, simX = { 0 };
            var refFill = new int[192]; var refOwner = new int[192];
            {
                // Viterbi over the rows: per-row rendering error + a penalty per band switch (keeps bands few and clean)
                int C = all.Count + 1;
                var cost = new double[192, C]; var fl = new int[192, C];
                for (int y = 0; y < 192; y++)
                {
                    bool w = y >= refc.WaterY;
                    var g = w ? wet : dry;
                    var errs = new double[g.Count + 1]; var fo = new int[g.Count + 1];
                    errs[0] = 0; for (int i = 1; i <= g.Count; i++) errs[i] = double.MaxValue;
                    int f0;
                    BgChooseErr(g, y, refc.D, refX, w ? wetRow[y] : dryRow[y], out f0, errs, fo);
                    for (int c = 0; c < C; c++) cost[y, c] = double.MaxValue;
                    cost[y, 0] = errs[0];
                    for (int i = 0; i < g.Count; i++) { cost[y, 1 + g[i].Idx] = errs[i + 1]; fl[y, 1 + g[i].Idx] = fo[i + 1]; }
                }
                double lambda = 256.0 * refX.Length * 600;
                var acc = new double[192, C]; var from = new int[192, C];
                for (int c = 0; c < C; c++) acc[0, c] = cost[0, c];
                for (int y = 1; y < 192; y++)
                    for (int c = 0; c < C; c++)
                    {
                        if (cost[y, c] == double.MaxValue) { acc[y, c] = double.MaxValue; continue; }
                        double bv = double.MaxValue; int bp = 0;
                        for (int p = 0; p < C; p++)
                        {
                            if (acc[y - 1, p] == double.MaxValue) continue;
                            double v = acc[y - 1, p] + (p == c ? 0 : lambda);
                            if (v < bv) { bv = v; bp = p; }
                        }
                        acc[y, c] = bv == double.MaxValue ? double.MaxValue : bv + cost[y, c]; from[y, c] = bp;
                    }
                int cur = 0; double bestEnd = double.MaxValue;
                for (int c = 0; c < C; c++) if (acc[191, c] < bestEnd) { bestEnd = acc[191, c]; cur = c; }
                for (int y = 191; y >= 0; y--)
                {
                    refOwner[y] = cur - 1;
                    if (cur > 0)
                    {
                        var L = all[cur - 1]; int r = y - (L.Base + refc.D * L.Num / 16);
                        L.Owned[r] = true; L.Fill[r] = fl[y, cur]; refFill[y] = fl[y, cur];
                    }
                    if (y > 0) cur = from[y, cur];
                }
            }
            foreach (var c in cfgs.Values)
            {
                if (c.Weight < 100 && (c.D & 7) != 0) continue;     // every 8 px is enough for the margins
                for (int y = 0; y < 192; y++)
                {
                    bool w = y >= c.WaterY;
                    var g = w ? wet : dry;
                    int f;
                    int li = BgChooseErr(g, y, c.D, simX, w ? wetRow[y] : dryRow[y], out f);
                    if (li < 0) continue;
                    var L = g[li]; L.RowWeight[y - (L.Base + c.D * L.Num / 16)] += c.Weight;
                }
            }
            // ---- palettes: split layers into BG palettes 6/7, quantize each to 15 colors ----
            BgAssignPalettes(all);

            // ---- choose stored tile rows: mandatory = owned; drop low-weight margin rows until map + CHR fit ----
            var keep = new List<bool[]>(); var mand = new List<bool[]>(); var trw = new List<double[]>();
            foreach (var L in all)
            {
                int nt = (L.Img.H + 7) / 8;
                var k = new bool[nt]; var m = new bool[nt]; var w = new double[nt];
                for (int r = 0; r < L.Img.H; r++)
                {
                    w[r / 8] += L.RowWeight[r];
                    if (L.Owned[r]) m[r / 8] = true;
                }
                for (int t = 0; t < nt; t++) k[t] = m[t] || w[t] > 0;
                keep.Add(k); mand.Add(m); trw.Add(w);
            }
            List<BgTile> tiles; ushort[] map; int rowsUsed; List<BgSeg> blocks;
            int dropped = 0;
            while (true)
            {
                BgBuildTiles(all, keep, out tiles, out map, out rowsUsed, out blocks);
                if (tiles.Count <= 256 && rowsUsed <= MapRows - 1) break;
                int bl = -1, bt = -1; double bw = double.MaxValue;
                for (int li = 0; li < all.Count; li++)
                    for (int t = 0; t < keep[li].Length; t++)
                        if (keep[li][t] && !mand[li][t] && trw[li][t] < bw) { bw = trw[li][t]; bl = li; bt = t; }
                if (bl < 0) break;
                keep[bl][bt] = false; dropped++;
            }
            if (rowsUsed > MapRows - 1) throw new Exception(th + ": owned rows exceed the BG2 map (" + rowsUsed + " tile rows)");
            int uniq = tiles.Count;
            if (tiles.Count > 256) BgReduceTiles(all, tiles, map);

            // ---- segments: margin blocks (far -> near) then owned runs (far -> near), per group ----
            var segs = new List<BgSeg>(); var fills = new List<int>();
            for (int pass = 0; pass < 2; pass++)
            {
                // margins = stored rows outside the owned bands (owned rows are painted later anyway: less overlap = faster)
                foreach (var b in blocks)
                {
                    if (b.Wet != (pass == 1)) continue;
                    var ow = all[b.Layer].Owned;
                    for (int r = b.R0; r < b.R1; )
                    {
                        if (ow[r]) { r++; continue; }
                        int r1 = r; while (r1 < b.R1 && !ow[r1]) r1++;
                        segs.Add(new BgSeg { Layer = b.Layer, R0 = r, R1 = r1, VBase = b.VBase, Wet = b.Wet });
                        r = r1;
                    }
                }
                foreach (var L in all)
                {
                    if (L.Wet != (pass == 1)) continue;
                    for (int r = 0; r < L.Img.H; )
                    {
                        if (!L.Owned[r]) { r++; continue; }
                        int r1 = r; while (r1 < L.Img.H && L.Owned[r1]) r1++;
                        BgSeg blk = null;
                        foreach (var b in blocks) if (b.Layer == L.Idx && b.R0 <= r && b.R1 >= r1) blk = b;
                        if (blk == null) throw new Exception(th + ": owned run without block");
                        var sg = new BgSeg { Layer = L.Idx, R0 = r, R1 = r1, VBase = blk.VBase, Wet = L.Wet };
                        bool hasFill = false;
                        for (int q = r; q < r1; q++)
                        {
                            int y = L.Base + refc.D * L.Num / 16 + q;
                            if (y >= 0 && y < 192 && ColDist(L.Fill[q], (L.Wet ? wetRow : dryRow)[y]) > 300) hasFill = true;
                        }
                        if (hasFill)
                        {
                            sg.FillIdx = fills.Count;
                            for (int q = r; q < r1; q++) fills.Add(Rgb555(L.Fill[q]));
                        }
                        segs.Add(sg);
                        r = r1;
                    }
                }
            }
            if (segs.Count > MaxSeg) throw new Exception(th + ": too many segments (" + segs.Count + ")");

            // ---- blob ----
            var chr = BgChr(all, tiles);
            var blob = new byte[BGV_CHR + chr.Length];
            blob[BGV_NLAYERS] = (byte)all.Count; blob[BGV_NSEG] = (byte)segs.Count;
            W16(blob, BGV_CHRBYTES, chr.Length);
            W16(blob, BGV_TROW, rowsUsed * 8); W16(blob, BGV_TLEN, Math.Min(120, (MapRows - rowsUsed) * 8));
            blob[BGV_NDRY] = (byte)dg.Length; blob[BGV_NWET] = (byte)wg.Length;
            for (int i = 0; i < dg.Length; i++) { blob[BGV_DRYSTART + i] = (byte)(192 * i / dg.Length); W16(blob, BGV_DRYCOL + 2 * i, dg[i]); }
            for (int i = 0; i < wg.Length; i++) { blob[BGV_WETSTART + i] = (byte)(192 * i / wg.Length); W16(blob, BGV_WETCOL + 2 * i, wg[i]); }
            foreach (var L in all) { blob[BGV_LNUM + L.Idx] = (byte)L.Num; W16(blob, BGV_LBASE + 2 * L.Idx, L.Base); }
            for (int i = 0; i < segs.Count; i++)
            {
                blob[BGV_SLAYER + i] = (byte)segs[i].Layer; blob[BGV_SFLAGS + i] = (byte)(segs[i].Wet ? 1 : 0);
                W16(blob, BGV_SR0 + 2 * i, segs[i].R0); W16(blob, BGV_SR1 + 2 * i, segs[i].R1); W16(blob, BGV_SVBASE + 2 * i, segs[i].VBase);
                W16(blob, BGV_SFILL + 2 * i, segs[i].FillIdx);
            }
            if (fills.Count > 192) throw new Exception(th + ": too many fill rows");
            W16(blob, BGV_NFILL, fills.Count);
            for (int i = 0; i < fills.Count; i++) W16(blob, BGV_FILL + 2 * i, fills[i]);
            for (int g = 0; g < 2; g++)
                for (int c = 0; c < 16; c++) W16(blob, BGV_PAL + 32 * g + 2 * c, c < bgGroupPal[g].Count ? Rgb555(bgGroupPal[g][c]) : 0);
            for (int i = 0; i < 2048; i++) W16(blob, BGV_MAP + 2 * i, map[i]);
            Array.Copy(chr, 0, blob, BGV_CHR, chr.Length);

            rep = all.Count + " layers, " + segs.Count + " segs, " + rowsUsed + " map rows, " + uniq + " tiles" +
                  (uniq > 256 ? " -> 256 (lossy)" : "") + (dropped > 0 ? ", " + dropped + " margin rows dropped" : "") +
                  ", pal " + bgGroupPal[0].Count + "+" + bgGroupPal[1].Count + (bgQuantized > 0 ? " (" + bgQuantized + " merged)" : "") +
                  ", " + blob.Length + " B";
            if (!string.IsNullOrEmpty(preview))
            {
                // the same two camera setups as the ROM test (snes/BACKGROUNDS.md): A = floor camera at x 0, B = 40 px up at x 300
                Directory.CreateDirectory(preview);
                string vn = th + "_" + (kind == 0 ? "dry" : kind == 1 ? "wet" : "mix");
                int wa = kind == 0 ? 192 : kind == 1 ? 0 : 120, wb = kind == 0 ? 192 : kind == 1 ? 0 : 160;
                BgPreview(blob, all, 0, wa, 0, Path.Combine(preview, vn + "_A.png"));
                BgPreview(blob, all, 40, wb, 300, Path.Combine(preview, vn + "_B.png"));
            }
            return blob;
        }

        static void W16(byte[] b, int o, int v) { b[o] = (byte)v; b[o + 1] = (byte)(v >> 8); }

        // ---- palettes ----
        static List<int>[] bgGroupPal = { new List<int>(), new List<int>() };
        static int bgQuantized;

        static void BgAssignPalettes(List<BgLayer> all)
        {
            int n = all.Count, bestMask = 0; long bestCost = long.MaxValue;
            var used = new List<HashSet<int>>();
            foreach (var L in all)
            {
                var h = new HashSet<int>();
                for (int s = 1; s < 16; s++) if (L.SlotCount[s] > 0) h.Add(L.Rgb[s]);
                used.Add(h);
            }
            for (int mask = 0; mask < (1 << n); mask++)
            {
                var g0 = new HashSet<int>(); var g1 = new HashSet<int>();
                for (int i = 0; i < n; i++) ((mask >> i & 1) == 0 ? g0 : g1).UnionWith(used[i]);
                long cost = Math.Max(0, g0.Count - 15) * 1000L + Math.Max(0, g1.Count - 15) * 1000L + Math.Abs(g0.Count - g1.Count);
                if (cost < bestCost) { bestCost = cost; bestMask = mask; }
            }
            bgQuantized = 0;
            foreach (var L in all) L.Group = bestMask >> L.Idx & 1;
            for (int g = 0; g < 2; g++)
            {
                // colors with pixel weights
                var cols = new List<int>(); var wts = new List<double>();
                foreach (var L in all)
                {
                    if (L.Group != g) continue;
                    for (int s = 1; s < 16; s++)
                    {
                        if (L.SlotCount[s] == 0) continue;
                        int k = cols.IndexOf(L.Rgb[s]);
                        if (k < 0) { cols.Add(L.Rgb[s]); wts.Add(L.SlotCount[s]); } else wts[k] += L.SlotCount[s];
                    }
                }
                // merge closest pairs until 15 remain; remember where each original color went
                var target = new List<int>(); for (int i = 0; i < cols.Count; i++) target.Add(i);
                var cur = new List<int>(cols); var cw = new List<double>(wts); var alive = new List<bool>();
                for (int i = 0; i < cols.Count; i++) alive.Add(true);
                int count = cols.Count;
                while (count > 15)
                {
                    int ba = -1, bb = -1; double bc = double.MaxValue;
                    for (int a = 0; a < cur.Count; a++) if (alive[a])
                        for (int b = a + 1; b < cur.Count; b++) if (alive[b])
                        {
                            double c = Math.Min(cw[a], cw[b]) * ColDist(cur[a], cur[b]);
                            if (c < bc) { bc = c; ba = a; bb = b; }
                        }
                    // weighted average into a, kill b
                    double wa = cw[ba], wb = cw[bb];
                    cur[ba] = MixRgb(cur[ba], cur[bb], wb / (wa + wb)); cw[ba] = wa + wb; alive[bb] = false; count--; bgQuantized++;
                    for (int i = 0; i < target.Count; i++) if (target[i] == bb) target[i] = ba;
                }
                var final = new List<int> { 0 }; var remap = new Dictionary<int, int>();
                for (int i = 0; i < cur.Count; i++) if (alive[i]) { remap[i] = final.Count; final.Add(cur[i]); }
                bgGroupPal[g] = final;
                foreach (var L in all)
                {
                    if (L.Group != g) continue;
                    L.SlotMap = new int[16];
                    for (int s = 1; s < 16; s++)
                        if (L.SlotCount[s] > 0) L.SlotMap[s] = remap[target[cols.IndexOf(L.Rgb[s])]];
                }
            }
        }

        static double ColDist(int a, int b)
        {
            int dr = ((a >> 16) & 255) - ((b >> 16) & 255), dg = ((a >> 8) & 255) - ((b >> 8) & 255), db = (a & 255) - (b & 255);
            return 3 * dr * dr + 4 * dg * dg + 2 * db * db;
        }

        static int MixRgb(int a, int b, double t)
        {
            int r = (int)Math.Round(((a >> 16) & 255) * (1 - t) + ((b >> 16) & 255) * t);
            int g = (int)Math.Round(((a >> 8) & 255) * (1 - t) + ((b >> 8) & 255) * t);
            int bl = (int)Math.Round((a & 255) * (1 - t) + (b & 255) * t);
            return (r << 16) | (g << 8) | bl;
        }

        // ---- tiles ----
        static byte[] FlipTile(byte[] p, int f)
        {
            var o = new byte[64];
            for (int y = 0; y < 8; y++)
                for (int x = 0; x < 8; x++)
                    o[y * 8 + x] = p[((f & 2) != 0 ? 7 - y : y) * 8 + ((f & 1) != 0 ? 7 - x : x)];
            return o;
        }

        static string TileKey(byte[] p, int g)
        {
            var c = new char[65]; c[0] = (char)g;
            for (int i = 0; i < 64; i++) c[i + 1] = (char)p[i];
            return new string(c);
        }

        /// <summary>Stores the kept tile rows of every layer into the 32x64 map (deduped with flips).</summary>
        static void BgBuildTiles(List<BgLayer> all, List<bool[]> keep, out List<BgTile> tiles, out ushort[] map, out int rowsUsed, out List<BgSeg> blocks)
        {
            tiles = new List<BgTile>(); map = new ushort[32 * MapRows]; blocks = new List<BgSeg>();
            var dict = new Dictionary<string, int>();
            tiles.Add(new BgTile { P = new byte[64], Group = -1 });
            int row = 0;
            foreach (var L in all)
            {
                var k = keep[L.Idx];
                for (int t = 0; t < k.Length; )
                {
                    if (!k[t]) { t++; continue; }
                    int t1 = t; while (t1 < k.Length && k[t1]) t1++;
                    blocks.Add(new BgSeg { Layer = L.Idx, R0 = t * 8, R1 = Math.Min(L.Img.H, t1 * 8), VBase = row * 8 - t * 8, Wet = L.Wet });
                    for (int tr = t; tr < t1; tr++, row++)
                    {
                        if (row >= MapRows) continue;
                        for (int cx = 0; cx < 32; cx++)
                        {
                            var p = new byte[64]; bool any = false;
                            for (int y = 0; y < 8; y++)
                            {
                                int iy = tr * 8 + y; if (iy >= L.Img.H) continue;
                                for (int x = 0; x < 8; x++)
                                {
                                    int s = L.Img.P[iy * 256 + cx * 8 + x];
                                    if (s != 0) { p[y * 8 + x] = (byte)L.SlotMap[s]; any = true; }
                                }
                            }
                            if (!any) { tiles[0].Count++; map[row * 32 + cx] = 0; continue; }
                            int idx = -1, flip = 0;
                            for (int f = 0; f < 4 && idx < 0; f++)
                            {
                                int v; if (dict.TryGetValue(TileKey(FlipTile(p, f), L.Group), out v)) { idx = v; flip = f; }
                            }
                            if (idx < 0) { idx = tiles.Count; dict[TileKey(p, L.Group)] = idx; tiles.Add(new BgTile { P = p, Group = L.Group }); }
                            tiles[idx].Count++;
                            map[row * 32 + cx] = (ushort)(idx | ((6 + L.Group) << 10) | ((flip & 1) << 14) | ((flip & 2) << 14));
                        }
                    }
                    t = t1;
                }
            }
            rowsUsed = row;
        }

        static double TileDist(byte[] a, byte[] b, List<int> pal, double cap)
        {
            double d = 0;
            for (int i = 0; i < 64; i++)
            {
                int x = a[i], y = b[i];
                if (x == y) continue;
                if (x == 0 || y == 0) d += 60000; else d += ColDist(pal[x], pal[y]);
                if (d >= cap) return d;
            }
            return d;
        }

        /// <summary>Lossy: merge the least-costly tile into its nearest neighbour (same palette, any flip) until 256 remain.</summary>
        static void BgReduceTiles(List<BgLayer> all, List<BgTile> tiles, ushort[] map)
        {
            int n = tiles.Count;
            var flips = new byte[n][][];
            for (int i = 0; i < n; i++) { flips[i] = new byte[4][]; for (int f = 0; f < 4; f++) flips[i][f] = FlipTile(tiles[i].P, f); }
            var nn = new int[n]; var nnF = new int[n]; var nnD = new double[n];
            Action<int> findNN = i =>
            {
                nn[i] = -1; nnD[i] = double.MaxValue;
                var pal = bgGroupPal[Math.Max(0, tiles[i].Group)];
                for (int j = 0; j < n; j++)
                {
                    if (j == i || tiles[j].MergedInto >= 0) continue;
                    if (j != 0 && tiles[j].Group != tiles[i].Group) continue;
                    for (int f = 0; f < 4; f++)
                    {
                        double d = TileDist(tiles[i].P, flips[j][f], pal, nnD[i]);
                        if (d < nnD[i]) { nnD[i] = d; nn[i] = j; nnF[i] = f; }
                        if (j == 0) break;
                    }
                }
            };
            for (int i = 1; i < n; i++) findNN(i);
            int alive = n;
            while (alive > 256)
            {
                int bi = -1; double bc = double.MaxValue;
                for (int i = 1; i < n; i++)
                    if (tiles[i].MergedInto < 0 && nn[i] >= 0 && tiles[i].Count * nnD[i] < bc) { bc = tiles[i].Count * nnD[i]; bi = i; }
                if (bi < 0) break;
                int to = nn[bi];
                tiles[bi].MergedInto = to; tiles[bi].MergeFlip = nnF[bi]; tiles[to].Count += tiles[bi].Count; alive--;
                for (int i = 1; i < n; i++) if (tiles[i].MergedInto < 0 && nn[i] == bi) findNN(i);
            }
            // resolve chains, renumber
            var newIdx = new int[n]; int k = 0;
            for (int i = 0; i < n; i++) newIdx[i] = tiles[i].MergedInto < 0 ? k++ : -1;
            for (int m = 0; m < map.Length; m++)
            {
                int e = map[m], t = e & 0x3FF, f = (e >> 14) & 3;
                while (tiles[t].MergedInto >= 0) { f ^= tiles[t].MergeFlip; t = tiles[t].MergedInto; }
                if (t == 0) { map[m] = 0; continue; }
                map[m] = (ushort)(newIdx[t] | (e & 0x1C00) | (f << 14));
            }
            var kept = new List<BgTile>();
            for (int i = 0; i < n; i++) if (tiles[i].MergedInto < 0) kept.Add(tiles[i]);
            tiles.Clear(); tiles.AddRange(kept);
        }

        static byte[] BgChr(List<BgLayer> all, List<BgTile> tiles)
        {
            var chr = new byte[tiles.Count * 32];
            for (int t = 0; t < tiles.Count; t++)
            {
                var p = tiles[t].P;
                for (int y = 0; y < 8; y++)
                    for (int x = 0; x < 8; x++)
                    {
                        int v = p[y * 8 + x], bit = 0x80 >> x;
                        if ((v & 1) != 0) chr[t * 32 + y * 2] |= (byte)bit;
                        if ((v & 2) != 0) chr[t * 32 + y * 2 + 1] |= (byte)bit;
                        if ((v & 4) != 0) chr[t * 32 + 16 + y * 2] |= (byte)bit;
                        if ((v & 8) != 0) chr[t * 32 + 16 + y * 2 + 1] |= (byte)bit;
                    }
            }
            return chr;
        }

        // ---- gradients (BGR555, top to bottom, max 16 bands over the 192-px playfield) ----
        static int[] BgDryGradient(string th)
        {
            if (!Art.HasPal(th + ".grad")) return new[] { Rgb555(0x5C94FC) };
            var g = Art.Pal(th + ".grad");
            var o = new int[Math.Min(16, g.Length - 1)];
            for (int i = 0; i < o.Length; i++) o[i] = Rgb555(NesPalette.RgbOf(g[i + 1]));
            return o;
        }

        /// <summary>Underwater gradient: palette THEME.wgrad if the art defines one, else derived from the average
        /// color of the "water" body tile in the theme's water palette (lighter at the top, darker at the bottom).</summary>
        static int[] BgWetGradient(string th)
        {
            if (Art.HasPal(th + ".wgrad"))
            {
                var g = Art.Pal(th + ".wgrad");
                var o = new int[Math.Min(16, g.Length - 1)];
                for (int i = 0; i < o.Length; i++) o[i] = Rgb555(NesPalette.RgbOf(g[i + 1]));
                return o;
            }
            var pal = Art.HasPal(th + ".water") ? Art.Pal(th + ".water") : Art.HasPal("default.water") ? Art.Pal("default.water") : Art.P(0x02, 0x12, 0x21);
            double r = 0, gg = 0, b = 0; int n = 0;
            if (Art.Has("water"))
            {
                var img = Art.Get("water");
                foreach (var p in img.P)
                {
                    if (p == 0 || p >= pal.Length) continue;
                    int c = NesPalette.RgbOf(pal[p]); r += (c >> 16) & 255; gg += (c >> 8) & 255; b += c & 255; n++;
                }
            }
            if (n == 0) { r = 0x18; gg = 0x50; b = 0xB0; n = 1; }
            r /= n; gg /= n; b /= n;
            var res = new int[12];
            for (int i = 0; i < 12; i++)
            {
                double f = 1.12 - 0.40 * i / 11.0;
                int R = (int)Math.Min(255, r * f), G = (int)Math.Min(255, gg * f), B = (int)Math.Min(255, b * f);
                res[i] = Rgb555((R << 16) | (G << 8) | B);
            }
            return res;
        }

        // ---- preview: simulate bg.s (painter + HDMA scroll) on the blob, PNG at 1x ----
        static int R16(byte[] b, int o) { return (short)(b[o] | (b[o + 1] << 8)); }

        static void BgPreview(byte[] blob, List<BgLayer> all, int d, int waterY, int camX, string png)
        {
            int nseg = blob[BGV_NSEG];
            var owner = new int[192];
            for (int y = 0; y < 192; y++) owner[y] = -1;
            var ly = new int[MaxLayers]; var hx = new int[MaxLayers];
            for (int L = 0; L < blob[BGV_NLAYERS]; L++)
            {
                int num = blob[BGV_LNUM + L];
                ly[L] = R16(blob, BGV_LBASE + 2 * L) + ((d * num) >> 4);
                hx[L] = (((camX & 0x7FF) * num) >> 3) & 255;
            }
            for (int s = 0; s < nseg; s++)
            {
                int L = blob[BGV_SLAYER + s]; bool wet = (blob[BGV_SFLAGS + s] & 1) != 0;
                int lo = wet ? waterY : 0, hi = wet ? 192 : waterY;
                int a = Math.Max(lo, ly[L] + R16(blob, BGV_SR0 + 2 * s)), e = Math.Min(hi, ly[L] + R16(blob, BGV_SR1 + 2 * s));
                for (int y = a; y < e; y++) owner[y] = s;
            }
            var pal = new int[32];
            for (int i = 0; i < 32; i++)
            {
                int c = blob[BGV_PAL + 2 * i] | (blob[BGV_PAL + 2 * i + 1] << 8);
                pal[i] = Exp555(c);
            }
            int ndry = blob[BGV_NDRY], nwet = blob[BGV_NWET];
            using (var bmp = new Bitmap(256, 224))
            {
                for (int y = 0; y < 224; y++)
                {
                    int back = 0;
                    if (y < 192)
                    {
                        bool w = y >= waterY; int n = w ? nwet : ndry, k = 0;
                        for (int i = 0; i < n; i++) if (blob[(w ? BGV_WETSTART : BGV_DRYSTART) + i] <= y) k = i;
                        int c = blob[(w ? BGV_WETCOL : BGV_DRYCOL) + 2 * k] | (blob[(w ? BGV_WETCOL : BGV_DRYCOL) + 2 * k + 1] << 8);
                        back = Exp555(c);
                        int so = owner[y];
                        if (so >= 0 && R16(blob, BGV_SFILL + 2 * so) != -1)
                        {   // hole fill color of this band row
                            int L = blob[BGV_SLAYER + so];
                            int fi = R16(blob, BGV_SFILL + 2 * so) + (y - ly[L]) - R16(blob, BGV_SR0 + 2 * so);
                            back = Exp555(blob[BGV_FILL + 2 * fi] | (blob[BGV_FILL + 2 * fi + 1] << 8));
                        }
                    }
                    for (int x = 0; x < 256; x++)
                    {
                        int col = back;
                        if (y < 192 && owner[y] >= 0)
                        {
                            int s = owner[y], L = blob[BGV_SLAYER + s];
                            int vofs = R16(blob, BGV_SVBASE + 2 * s) - ly[L];
                            int my = (y + vofs) & 511, mx = (x + hx[L]) & 255;
                            int e = blob[BGV_MAP + 2 * ((my >> 3) * 32 + (mx >> 3))] | (blob[BGV_MAP + 2 * ((my >> 3) * 32 + (mx >> 3)) + 1] << 8);
                            int t = e & 0x3FF, px = mx & 7, py = my & 7;
                            if ((e & 0x4000) != 0) px = 7 - px;
                            if ((e & 0x8000) != 0) py = 7 - py;
                            int o = BGV_CHR + t * 32, bit = 0x80 >> px;
                            int v = ((blob[o + py * 2] & bit) != 0 ? 1 : 0) | ((blob[o + py * 2 + 1] & bit) != 0 ? 2 : 0) |
                                    ((blob[o + 16 + py * 2] & bit) != 0 ? 4 : 0) | ((blob[o + 16 + py * 2 + 1] & bit) != 0 ? 8 : 0);
                            if (v != 0) col = pal[(((e >> 10) & 7) - 6) * 16 + v];
                        }
                        bmp.SetPixel(x, y, Color.FromArgb(255, (col >> 16) & 255, (col >> 8) & 255, col & 255));
                    }
                }
                bmp.Save(png, ImageFormat.Png);
            }
        }
    }
}
