# Builds snes\build\smb4.sfc (SNES LoROM FastROM) from snes\src\*.s plus the generated snes\build\gen\*.s.
# Usage: powershell -ExecutionPolicy Bypass -File snes\build.ps1 [-Tools <path to smb4tools.exe>] [-Out <dir>] [-NoExport]
#   -Tools   smb4tools.exe used for `snes-export` (default: bin\smb4tools.exe). Agents pass their private .agentbin copy.
#   -Out     output dir for objects + ROM (default snes\build). Agents use snes\build-<name> to avoid clobbering.
#   -NoExport  skip asset conversion (reuse <Out>\gen).
param([string]$Tools = '', [string]$Out = '', [switch]$NoExport)
$ErrorActionPreference = 'Stop'
if ($Tools -ne '') { $Tools = (Resolve-Path $Tools).Path }
$snes = $PSScriptRoot
$root = Split-Path $snes -Parent
if ($Tools -eq '') { $Tools = Join-Path $root 'bin\smb4tools.exe' }
if ($Out -eq '') { $Out = Join-Path $snes 'build' }
New-Item -ItemType Directory -Force $Out, "$Out\obj", "$Out\gen" | Out-Null
$ca65 = "$snes\tools\cc65\bin\ca65.exe"; $ld65 = "$snes\tools\cc65\bin\ld65.exe"
if (-not $NoExport) {
    Push-Location $root
    & $Tools snes-export "$Out\gen"
    $rc = $LASTEXITCODE
    Pop-Location
    if ($rc -ne 0) { Write-Host "EXPORT FAILED" -ForegroundColor Red; exit 1 }
}
# Entity registry: every snes\src\ent_*.s declares   ;@entity NAME codes=abc   (codes = level spawn chars, optional)
# and exports NAME_vt (see DESIGN.md "Entities"). Generated: gen\ent_ids.inc (ET_NAME ids, stable = sorted by NAME)
# and gen\ent_table.s (ent_vtables: far pointer per id; ent_spawn_map: 128-byte ASCII spawn char -> id).
$ents = @()
foreach ($f in Get-ChildItem "$snes\src" -Filter 'ent_*.s' -ErrorAction SilentlyContinue) {
    foreach ($m in (Select-String -Path $f.FullName -Pattern '^\s*;@entity\s+([A-Z0-9_]+)(?:\s+codes=(\S+))?')) {
        $ents += [pscustomobject]@{ Name = $m.Matches[0].Groups[1].Value; Codes = $m.Matches[0].Groups[2].Value; File = $f.Name }
    }
}
$ents = @($ents | Sort-Object Name)
$dup = $ents | Group-Object Name | Where-Object Count -gt 1
if ($dup) { Write-Host ("ENTITY NAME CLASH: " + ($dup.Name -join ', ')) -ForegroundColor Red; exit 1 }
$ids = @('; generated by snes\build.ps1 from ;@entity lines in snes\src\ent_*.s - do not edit', 'ET_NONE = 0')
$tab = @('; generated by snes\build.ps1 - do not edit', '.p816', '.export ent_vtables, ent_spawn_map, ent_count')
$map = New-Object int[] 128
for ($i = 0; $i -lt $ents.Count; $i++) {
    $e = $ents[$i]; $ids += ('ET_{0} = {1}' -f $e.Name, ($i + 1)); $tab += ('.import {0}_vt' -f $e.Name)
    foreach ($ch in $e.Codes.ToCharArray()) {
        if ($map[[int]$ch] -ne 0) { Write-Host "SPAWN CODE '$ch' claimed twice ($($e.Name))" -ForegroundColor Red; exit 1 }
        $map[[int]$ch] = $i + 1
    }
}
$ids += ('ET_COUNT = {0}' -f ($ents.Count + 1))
$tab += '.segment "RODATA"', 'ent_count: .word ET_COUNT_', ('ET_COUNT_ = {0}' -f ($ents.Count + 1)), 'ent_vtables:', '    .faraddr 0              ; ET_NONE'
foreach ($e in $ents) { $tab += ('    .faraddr {0}_vt' -f $e.Name) }
$tab += 'ent_spawn_map:'
for ($r = 0; $r -lt 128; $r += 16) { $tab += ('    .byte ' + (($map[$r..($r + 15)] | ForEach-Object { $_ }) -join ',')) }
Set-Content "$Out\gen\ent_ids.inc" $ids -Encoding ascii
Set-Content "$Out\gen\ent_table.s" $tab -Encoding ascii

$objs = @()
$srcs = @(Get-ChildItem "$snes\src" -Filter *.s) + @(Get-ChildItem "$Out\gen" -Filter *.s -ErrorAction SilentlyContinue)
foreach ($s in $srcs) {
    $o = "$Out\obj\" + $s.BaseName + '.o'
    if ($s.DirectoryName -ne "$snes\src") { $o = "$Out\obj\gen_" + $s.BaseName + '.o' }
    & $ca65 --cpu 65816 -I "$snes\src" -I "$Out\gen" --bin-include-dir "$Out\gen" -g $s.FullName -o $o
    if ($LASTEXITCODE -ne 0) { Write-Host "ASSEMBLY FAILED: $($s.Name)" -ForegroundColor Red; exit 1 }
    $objs += $o
}
$rom = "$Out\smb4.sfc"
& $ld65 -C "$snes\lorom.cfg" -m "$Out\smb4.map" --dbgfile "$Out\smb4.dbg" -o $rom @objs
if ($LASTEXITCODE -ne 0) { Write-Host "LINK FAILED" -ForegroundColor Red; exit 1 }
# fix the internal checksum (LoROM header at file offset $7FC0)
$b = [IO.File]::ReadAllBytes($rom)
$b[0x7FDC] = 0xFF; $b[0x7FDD] = 0xFF; $b[0x7FDE] = 0; $b[0x7FDF] = 0
$sum = 0; foreach ($x in $b) { $sum = ($sum + $x) -band 0xFFFF }
$b[0x7FDE] = $sum -band 0xFF; $b[0x7FDF] = ($sum -shr 8) -band 0xFF
$c = $sum -bxor 0xFFFF; $b[0x7FDC] = $c -band 0xFF; $b[0x7FDD] = ($c -shr 8) -band 0xFF
[IO.File]::WriteAllBytes($rom, $b)
Write-Host ("Built {0} ({1:N0} KB)" -f $rom, ($b.Length / 1KB)) -ForegroundColor Green
